### ISSUE TITLE
Smart filter filters modes given to you regardless of recent speakers

### ISSUE THREAD

**Issue by arza-zara** [weechat/weechat#530] opened 2015-09-13 08:55 UTC
client1:

```
/filter add smart * irc_smart_filter *
connect as nick1
join a channel
say something
```

client2:

```
join the same channel
say something
/op nick1
```

-> the mode change is filtered in client1

**Comment by Mikaela** [comment] 2017-01-28 18:08
Duplicate of https://github.com/weechat/weechat/issues/113 ?

**Comment by arza-zara** [comment] 2017-01-29 11:01
This issue is about the bug of smart filter *always* filtering modes given to you regardless of recent speakers, however my solution is to *never* filter modes given to you. If someone thinks an option is necessary (I don't), I can make one.

Contrary to the discussion in #113, currently the decision of smart filtering a mode is made from *only the targets* of modes ([irc-mode.c:452](https://github.com/weechat/weechat/blob/658b166a41b9db1d7c341fc323a8efe4308bfc77/src/plugins/irc/irc-mode.c#L452)) and modes to you are always filtered because irc_channel_speaking->time_last_message isn't updated for yourself.

**Closed** 2017-01-29 12:38 UTC
Labels: bug
