### ISSUE TITLE
Cmake won't compile python plugin

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#1383] opened 2019-07-27 02:16 UTC
###  Summary

When building Weechat using cmake, the python plugin doesn't get compiled. There are two problems:

1. cmake finds different versions of python
2. cmake doesn't produce an error or warning that it won't compile python

This problem arises from ab81128a7aa7944201725000420662b33f22d1ec and can be fixed by passing -DENABLE_PYTHON2=ON to cmake. But I'm guessing that this is still a bug as no warning is produced.

### Current behavior

Currently Weechat compiles as if nothing is wrong but then shows this in the core buffer: `weechat =!= Error: API mismatch for plugin "/usr/local/lib/weechat/plugins/python.so" (current API:"20190624-01", plugin API: "20190228-01"), failed to load`. I looked into `weechat/build/Makefile`, and there were no mentions of python whatsoever, so the problem was with the `weechat/build # cmake ..` stage.

Finally I found that cmake finds mismatching python files, probably due to the fact that I have python 2 installed from the repos and python 3 built from sources:

    # echo 'message("oysters ${PYTHON_VERSION} ${PYTHON_INCLUDE_PATH} ${PYTHON_LIBRARY} ${PYTHON_LFLAGS}")' >> ~/weechat/cmake/FindPython.cmake

    # cmake --trace-source --trace-expand .. 2>&1 | grep '^oysters'
    oysters 3.7 /usr/local/include/python3.7m /usr/lib/arm-linux-gnueabihf/libpython2.7.so -lcrypt -lpthread -ldl  -lutil -Xlinker -export-dynamic

Even though this looks to be a mistake, cmake sets `PYTHON_FOUND`. I'm only guessing that this configuration fails silently later on.

---

- WeeChat version: 93cd05bdd8f04721e4400eca0e0e776877e33be9 (current master)
- OS, distribution and version: Raspbian GNU/Linux 9 (stretch) Linux 4.19.42-v7+ armv7l GNU/Linux

**Comment by flashcode** [comment] 2019-07-31 21:02
Hi,
Now that #1382 is merged, the Python detection has completely changed.
Could you please try to compile again with these changes and tell me if it's OK now?

**Comment by oakkitten** [comment] 2019-08-03 11:43
tried compiling the current master. while the python plugin gets compiled for both python2 and python3 without any problems, and python2 works fine, when i try to load python3 i get the following error:

    Error: unable to load plugin "/usr/local/lib/weechat/plugins/python.so":
    /usr/local/lib/weechat/plugins/python.so: undefined symbol: forkpty

this seems to be the same as issue #420, and `LD_PRELOAD=/lib64/libutil.so.1` helps.

otoh, i noticed just now (since i wasn't loading it) that the ruby plugin also silently fails to compile due to the lack of dependencies. there's no warning, the only clue is that there's no `--   found ruby` line after `-- checking for one of the modules 'ruby-2.6;...'`, so the problem No 2 remains.

(in fact, if i'm explicitly requesting a feature from cmake, i'm probably expecting it to abort the compilation altogether if it can't be implemented, not just a warning.)

**Comment by flashcode** [comment] 2019-08-03 14:02
> Error: unable to load plugin "/usr/local/lib/weechat/plugins/python.so":
> /usr/local/lib/weechat/plugins/python.so: undefined symbol: forkpty

You seem to use a custom Python installation, could you please try with the standard Python from your distribution?
Same remark for ruby if ever you recompiled it.

**Comment by flashcode** [comment] 2019-08-03 14:03
Are you using Python and Ruby from your distribution or are you using a custom installation (or compiled by you)?

**Comment by oakkitten** [comment] 2019-08-03 17:55
python 3.7 i compiled myself, the rest comes from my distro. as for the ruby, i didn't have `ruby3.2-dev` installed, so ruby couldn't be compiled anyway. installing the package fixed it. still, there was no warning, even though i am *explicitly* enabling an optional module (`cmake .. -DENABLE_RUBY=ON`). compare this to behavior of other apps, e.g. compiling nginx with an optional module (`./configure --with-google_perftools_module`) with missing dependencies results in not even a warning but an abort:

    ./configure: error: the Google perftools module requires the Google perftools
    library. You can either do not enable the module or install the library.

**Comment by kashike** [comment] 2019-08-05 22:54
I'm encountering the same issue (`Error: API mismatch for plugin "/usr/....`) as of 210e8648991903738d91dfeac22de107e9cabc7d.

**Comment by oakkitten** [comment] 2019-08-10 00:10
not really sure where to put this so i'll just put this here. to compile weechat with python3, i added `set(PYTHON_LDFLAGS "${PYTHON_LDFLAGS} -lutil")` to `~/weechat/cmake/FindPython.cmake`, which worked fine. then i added `/py2` and `/py3` commands as per the [python 3 guide](https://weechat.org/scripts/python3/).

the commands work fine, unless i try to go from py2 to py3 and back, or vice versa, whereupon weechat crashes with this:

```
#4  <signal handler called>
No locals.
#5  strlen () at ../sysdeps/arm/armv6/strlen.S:26
No locals.
#6  0x75bb3328 in PyUnicode_FromString (u=0x74e63fa8 <error: Cannot access memory at address 0x74e63fa8>)
    at Objects/unicodeobject.c:2129
        size = <optimized out>
#7  0x75ccb948 in list_builtin_module_names () at ./Python/sysmodule.c:1617
        name = <optimized out>
        list = 0x74fd31e8
        i = <optimized out>
#8  _PySys_BeginInit (sysmod=sysmod@entry=0x7ee9ffd0) at ./Python/sysmodule.c:2349
        m = 0x74f762a0
        sysdict = 0x74f763c0
        res = <optimized out>
        __func__ = "_PySys_BeginInit"
#9  0x75cc51f0 in _Py_InitializeCore_impl (interp_p=interp_p@entry=0x7eea00a8, core_config=core_config@entry=0x7eea0008)
    at Python/pylifecycle.c:756
        interp = 0x2015fb0
        err = {prefix = 0x75cc51f0 <_Py_InitializeCore_impl+332> "\b", msg = 0x7eea0010 "\001", user_err = 0}
        __func__ = "_Py_InitializeCore_impl"
        tstate = 0x1fe4e10
        modules = 0x75071f00
        sysmod = 0x7eea0010
        bimod = <optimized out>
        pstderr = <optimized out>
...
```

switching once is ok. reloading the same version multiple times is ok. it's switching twice that leads to the crash.

**Comment by flashcode** [comment] 2019-08-10 07:24
Now that WeeChat uses pkg-config to find and compile with Python, I think your compilation problem is caused by your custom install of Python, so as I can not reproduce the problem, I close the issue.

For the crash between switch from Python 2 to 3, you could open a separate issue, but anyway this is not a normal use case in the future (Python 2 should not be used any more except for testing purposes).

**Closed by flashcode** 2019-08-10 07:24 UTC
Labels: bug, waiting info
