### ISSUE TITLE
Autojoin doesn't work after upgrade to WeeChat 2.7.1-1

### ISSUE THREAD

**Issue by ChaiTRex** [weechat/weechat#1451] opened 2020-02-23 05:29 UTC
## Bug summary

With an upgrade to WeeChat 2.7.1-1 on Ubuntu Bionic having installed a previous version via https://weechat.org/download/debian/

## Steps to reproduce

1. Set up autojoin
2. Connect to server
3. Note that it works
4. Upgrade to WeeChat 2.7.1-1
5. Start WeeChat
6. Note that autojoin doesn't work and that any attempt to send a message in an autoopened channel buffer produces the error: `=!= | irc: this buffer is not a channel!`
7. Note that manually joining works

## Current behavior

Autojoined channels aren't autojoined.

## Expected behavior

Autojoined channels are autojoined.

## Suggested solutions

None.

## Additional information

None.

---

- WeeChat version: 2.7.1-1
- OS, distribution and version: Ubuntu Linux Bionic (18.04.4)

**Comment by flashcode** [comment] 2020-02-23 07:36
Hi,

Nothing has changed in 2.7.1 about autojoin (compared to 2.7).

The message you mentioned in 6 is probably related to #1417? (so a known issue, for now I have no fix for this).

Anyway I would need more info to reproduce the problem:

- are you connecting to IRC server with SSL or not?
- when you say "Upgrade to WeeChat 2.7.1-1", are you using command `/upgrade`?
- what's the value of this option: `irc.look.buffer_open_before_autojoin`?

Maybe the autojoin does not happen because of a server connection issue?

**Comment by weechatter** [comment] 2020-02-23 07:49
looks like the format of your autojoin option is not correct, please paste your autojoin option or read the /help on autojoin option. Also check your scripts, /script list -o and paste the output here.
For me the autojoin works as expected, no problems

**Comment by ChaiTRex** [comment] 2020-02-23 19:08
Yes, I connect via SSL. I think the connection is fine because I can still manually join the channels.

I didn't use the command `/upgrade`, I upgraded via Ubuntu's package manager using WeeChat officially provided packages using `apt upgrade` and then I exited WeeChat, restarted my computer, and started WeeChat.

`irc.look.buffer_open_before_autojoin` is set to `on`. `irc.server.freenode.autojoin` is set to `"##math,##categorytheory,##algorithms,##smt,##java,#haskell,#numerical-haskell,##rust,##adventofcode,##adventofcode-help,##adventofcode-spoilers"`

It's unlikely that my autojoin settings are incorrect. As I pointed out, autojoin worked fine before the upgrade, and the settings haven't been changed. Also, the autojoined channels from the options still properly open buffers for them on WeeChat startup on this new version.

`/script list -o` produces `Scripts loaded: buffer_autoset.py 1.1`. The contents of `buffer_autoset.conf` are:

    #
    # weechat -- buffer_autoset.conf
    #
    # WARNING: It is NOT recommended to edit this file by hand,
    # especially if WeeChat is running.
    #
    # Use /set or similar command to change settings in WeeChat.
    #
    # For more info, see: https://weechat.org/doc/quickstart
    #
    [look]
    instant = on
    timer = 1
    [buffer]
    irc.freenode.#haskell.hotlist_max_level_nicks = "hackage:-1"

**Comment by flashcode** [comment] 2020-02-23 19:48
Could you please show the whole server settings with `/server listfull freenode`? (replace freenode by the appropriate name if needed).
Also are these double `##` normal in your autojoin list?

**Comment by ChaiTRex** [comment] 2020-02-23 20:42
Servers with "freenode":
    
    Server: freenode [connected], nick: ChaiTRex
      addresses. . . . . . : 'ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion/7000'
      proxy. . . . . . . . : 'tor'
      ipv6 . . . . . . . . :   (on)
      ssl. . . . . . . . . : on
      ssl_cert . . . . . . : '%h/certs/freenode.pem'
      ssl_password . . . . :   (hidden)
      ssl_priorities . . . :   ('NORMAL:-VERS-SSL3.0')
      ssl_dhkey_size . . . :   (2048)
      ssl_fingerprint. . . :   ('')
      ssl_verify . . . . . : off
      password . . . . . . :   (hidden)
      capabilities . . . . :   ('')
      sasl_mechanism . . . : 'external'
      sasl_username. . . . : 'ChaiTRex'
      sasl_password. . . . :   (hidden)
      sasl_key. .  . . . . :   ('')
      sasl_timeout . . . . : 120 seconds
      sasl_fail. . . . . . : 'reconnect'
      autoconnect. . . . . : on
      autoreconnect. . . . :   (on)
      autoreconnect_delay. :   (10 seconds)
      nicks. . . . . . . . :   ('ChaiTRex,Chai-T-Rex')
      nicks_alternate. . . :   (on)
      username . . . . . . :   ('ChaiTRex')
      realname . . . . . . :   ('Chai T. Rex')
      local_hostname . . . :   ('')
      usermode . . . . . . :   ('')
      command. . . . . . . : '/query lambdabot'
      command_delay. . . . :   (0 seconds)
      autojoin . . . . . . : '##math,##categorytheory,##algorithms,##smt,##java,#haskell,#numerical-haskell,##rust,##adventofcode,##adventofcode-help,##adventofcode-spoilers'
      autorejoin . . . . . :   (off)
      autorejoin_delay . . :   (30 seconds)
      connection_timeout . :   (60 seconds)
      anti_flood_prio_high :   (2 seconds)
      anti_flood_prio_low. :   (2 seconds)
      away_check . . . . . :   (0 minutes)
      away_check_max_nicks :   (25)
      msg_kick . . . . . . :   ('')
      msg_part . . . . . . :   ('')
      msg_quit . . . . . . :   ('')
      notify . . . . . . . :   ('')
      split_msg_max_length :   (512)
      charset_message. . . :   ('message')

The channel names include the `##`, so yes.

**Comment by flashcode** [comment] 2020-02-23 20:48
So if the autojoin doesn't happen at all, please paste the output of server buffer when WeeChat is connecting to the server.

**Comment by ChaiTRex** [comment] 2020-02-23 21:15
I tried connecting again and autojoin now works, so it appears the problem is intermittent. Here is the output when connecting earlier when autojoin failed:

    00:14:28  -- | irc: connecting to server ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion/7000 (SSL) via socks5 proxy 127.0.0.1/9050...
    00:14:30  -- | gnutls: connected using 2048-bit Diffie-Hellman shared secret exchange
    00:14:30  -- | gnutls: receiving 2 certificates
    00:14:30  -- |  - certificate[1] info:
    00:14:30  -- |    - subject `CN=zettel.freenode.net', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x03c7dcba14bb3c915de6792c990c0e364d49, RSA key 4096 bits, signed using RSA-SHA256, activated `2020-02-17 05:03:07 UTC', expires
                 | `2020-05-17 05:03:07 UTC', pin-sha256="4BsxgFbZeMQrLT+y24GrAxVZvwR+MehgX5gHobuPow0="
    00:14:30  -- |  - certificate[2] info:
    00:14:30  -- |    - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17
                 | 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="
    00:14:30 =!= | gnutls: the hostname in the certificate does NOT match "ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion"
    00:14:30  -- | gnutls: peer's certificate is trusted
    00:14:30  -- | gnutls: sending one certificate
    00:14:30  -- |  - client certificate info (/home/ubuntu/.weechat/certs/freenode.pem):
    [REDACTED]
    00:14:30  -- | irc: connected to ajnvpgl6prmkb7yktvue6im5wiedlz2w32uhcwaamdiecdrfpwwgnlqd.onion/7000 (127.0.0.1)
    00:14:30  -- | zettel.freenode.net: *** Looking up your hostname...
    00:14:30  -- | zettel.freenode.net: *** Couldn't look up your hostname
    00:14:31  -- | irc: client capability, server supports: extended-join tls multi-prefix identify-msg account-notify chghost sasl cap-notify away-notify
    00:14:31  -- | irc: client capability, requesting: sasl
    00:14:31  -- | irc: client capability, enabled: sasl
    00:14:32  -- | You are now logged in as ChaiTRex. (ChaiTRex!ChaiTRex@unaffiliated/chaitrex)
    00:14:32  -- | SASL authentication successful
    00:14:33  -- | zettel.freenode.net: *** Spoofing your IP
    00:14:33  -- | Welcome to the freenode Internet Relay Chat Network ChaiTRex
    00:14:33  -- | Your host is zettel.freenode.net[127.0.6.5/17110], running version ircd-seven-1.1.9
    00:14:33  -- | This server was created Thu Dec 19 2019 at 20:31:25 UTC
    00:14:33  -- | zettel.freenode.net ircd-seven-1.1.9 DOQRSZaghilopsuwz CFILMPQSbcefgijklmnopqrstuvz bkloveqjfI
    00:14:33  -- | CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstuz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
    00:14:33  -- | CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 SAFELIST ELIST=CTU CPRIVMSG :are supported by this server
    00:14:33  -- | CNOTICE WHOX ETRACE KNOCK :are supported by this server
    00:14:33  -- | There are 85 users and 81055 invisible on 29 servers
    00:14:33  -- | 32 :IRC Operators online
    00:14:33  -- | 42988 :channels formed
    00:14:33  -- | I have 235 clients and 1 servers
    00:14:33  -- | 235 270 :Current local users 235, max 270
    00:14:33  -- | 81140 87738 :Current global users 81140, max 87738
    00:14:33  -- | Highest connection count: 271 (270 clients) (27210 connections received) 
    00:14:33  -- | - zettel.freenode.net Message of the Day -
    00:14:33  -- | - Welcome to zettel.freenode.net, our tor hidden service.
    00:14:33  -- | - Welcome to freenode - supporting the free and open source 
    00:14:33  -- | - software communities since 1998.
    00:14:33  -- | -  
    00:14:33  -- | - By connecting to freenode you indicate that you have read and
    00:14:33  -- | - accept our policies and guidelines as set out on https://freenode.net
    00:14:33  -- | -  
    00:14:33  -- | - In the event that you observe behaviour that contravenes our policies,
    00:14:33  -- | - please notify a volunteer staff member via private message, or send us an
    00:14:33  -- | - e-mail to complaints@freenode.net -- we will do our best to address the
    00:14:33  -- | - situation within a reasonable period of time, and we may request further
    00:14:33  -- | - information or, as appropriate, involve other parties such as channel operators
    00:14:33  -- | - Group Contacts representing an on-topic group.
    00:14:33  -- | -  
    00:14:33  -- | - freenode runs an open proxy scanner.
    00:14:33  -- | -  
    00:14:33  -- | - If you are looking for assistance, you may be able to find a list of
    00:14:33  -- | - volunteer staff on '/stats p' (shows only on-call staff) or by joining
    00:14:33  -- | - #freenode and using the '/who freenode/staff/*' command. You may message
    00:14:33  -- | - any of us at any time. Please note that freenode predominantly provides
    00:14:33  -- | - assistance via private message, and while we have a network channel the
    00:14:33  -- | - primary venue for support requests is via private message to a member
    00:14:33  -- | - of the volunteer staff team.
    00:14:33  -- | -
    00:14:33  -- | - From time to time, volunteer staff may send server-wide notices relating to
    00:14:33  -- | - the project, or the communities that we host. The majority of such notices
    00:14:33  -- | - will be sent as wallops, and you can '/mode <yournick> +w' to ensure that you
    00:14:33  -- | - do not miss them. Important messages relating to the freenode project, including
    00:14:33  -- | - notices of upcoming maintenance and other scheduled downtime will be issued as 
    00:14:33  -- | - global notices.
    00:14:33  -- | -
    00:14:33  -- | - Representing an on-topic project? Don't forget to register, more information
    00:14:33  -- | - can be found on the https://freenode.net website under "Group Registration".
    00:14:33  -- | -  
    00:14:33  -- | - Thank you also to our server sponsors for the sustained support in keeping the
    00:14:33  -- | - network going for close to two decades.
    00:14:33  -- | -  
    00:14:33  -- | - Thank you for using freenode!
    00:14:33  -- | End of /MOTD command.
    00:14:33  -- | User mode [+Zi] by ChaiTRex
    00:14:33  -- | gateway/tor-sasl/chaitrex :hostname reset by syn.

**Comment by flashcode** [comment] 2020-03-02 11:57
I see nothing wrong here, could you please check in `/server raw` if the JOIN command is really sent to the server, when the autojoin seems to "fail"?

**Closed** 2020-04-11 08:08 UTC
Labels: bug, not reproduced

**Comment by 0x5c** [comment] 2026-02-03 22:35
I've hit this bug after upgrading from `3.8` to `4.6.3`. It happens intermittently, and only on non-tls connections.

In the `/server raw` tab, I see an outgoing `JOIN <autojoin channel>` immediately following reception of `RPL_WELCOME`. After that `JOIN`, there a no more incoming messages displayed in the raw tab. In that limbo state CTCP `VERSION` and `PING` sent by another client remain unanswered. This lasts until the server issues a ping timeout and closes the TCP connection, causing weechat to reattempt connection.

In that reattempt, connection to the server succeeds, server pings and CTCP are being responded to, but the behaviour of https://github.com/weechat/weechat/issues/1873 is observed.

It seems to me like a race-condition makes weechat `JOIN` a channel before being done receiving numerics `001` through `005`.
