### ISSUE TITLE
Weechat 1.1 improperly discovers the terminal charset (Mac OS X)

### ISSUE THREAD

**Issue by emmanuelbernard** [weechat/weechat#306] opened 2015-01-16 17:52 UTC
On the same terminal, running `/charset`, I receive different results if I use Weechat 1.0.1 vs 1.1

    #1.0.1
    charset: terminal: UTF-8, internal: UTF-8
    #1.1
    charset: terminal: US-ASCII, internal: UTF-8

This causes my unicode characters in weechat.conf (like ⤷) to be erased and replaced by ?.

I supposed it might be a regression as weechat 1.0.1 runs as expected. I installed Weechat via homebrew.

I try to play with charset.conf but I could not force the terminal charset with what I tried.

**Comment by flashcode** [comment] 2015-01-16 19:15
I can't reproduce this problem on Linux (and I have no way to test on Mac OS X).
Are you sure that both versions are compiled with exactly same options and linked with same libs?
If possible please try to compile yourself both versions with exactly same cmake options.

**Comment by flashcode** [comment] 2015-01-16 20:36
And by the way, I think nothing has changed between 1.0.1 and 1.1 about (terminal) charset detection (that's why I think something has changed on your build or your environment).

**Comment by erickpintor** [comment] 2015-01-16 21:48
I started to have the same issue after a ```brew upgrade```. I tried to do a downgrade to the previous version but, I got the same issue again.

It's probably due some other dependency that has been updated while executing the brew upgrade.

**Comment by flashcode** [comment] 2015-01-17 07:26
OK, then I close this issue.
If you think there's still a problem with charset, but another problem, feel free to open a new issue then.

**Closed by flashcode** 2015-01-17 07:26 UTC
Labels: bug, not reproduced, waiting info

**Comment by erickpintor** [comment] 2015-01-17 17:43
You may want to try this ```export LANG=en_US.UTF-8 LC_CTYPE="en_US.UTF-8"```
It seems to fix the issue for me.

**Comment by Mikaela** [comment] 2015-01-17 18:02
There is also `LC_ALL` which controls all the others. I have `export LC_ALL=fi_FI.UTF-8` in my zshrc.

With tmux it's possible to use the following options, but the utf8 once have been called as dangerous (making troubleshooting more difficult if terminal really isn't UTF-8 and tmux forces it or something):

```tmux
set -g utf8
set-window-option -g utf8 on
set -g default-terminal "screen-256color"
```

(the last is unrelated, but you might want it too.) I don't know how this happens with screen, but should be possible there too.

**Comment by emmanuelbernard** [comment] 2015-01-19 08:32
Thanks

    export LANG=en_US.UTF-8 LC_CTYPE="en_US.UTF-8"

did the trick. I was missing LC_CTYPE in my case.

I tried to find the culprit lib but could not.
