### ISSUE TITLE
Mouse wheel up/down fill input field with random chars when on left edge, with mouse support enabled

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [weechat/weechat#1893] opened 2023-03-16 20:38 UTC
## Bug summary
Using mouse support on `xfce4-terminal` and `tmux` as terminal multiplexer, when you put the mouse pointer all to the left of the screen, really on the edge, with the buffer list on the left (default) and you use mouse wheel up/down , a weird behaviour occurs, inputting random chars in the input field.

Worth to mention that I have no issue whatsoever with `screen` as terminal multiplexer or directly running weechat.

## Steps to reproduce

1. Run weechat under tmux
2. Enable mouse support
3. Place your mouse on the left edge and use mouse wheel up/down
4. Watch weird chars appearing in the input field

## Current behavior
[weird.webm](https://user-images.githubusercontent.com/25697531/225744525-27183297-0609-4d8e-9039-a371dddcead0.webm)

## Expected behavior
Buffer list should be scrolled up/down

---

- WeeChat version: WeeChat 3.9-dev (git: v3.8-124-gb21bc6331) [compiled on Mar 16 2023 12:02:05]
- OS, distribution and version: Ubuntu 22.04.2 LTS
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by flashcode** [comment] 2023-03-17 08:28
It seems SGR mouse coordinates are received and are not (yet) supported.

For example this sequence: `^[[<65;0;14M`.
As `^[[<` is not supported, the rest is just sent as input of the buffer.

I'm looking to add support of SGR coordinates.

**Comment by flashcode** [comment] 2023-03-18 09:29
I think the problem could come from tmux, as it happens only in tmux (with some terminals only though).

So I opened a bug here: https://github.com/tmux/tmux/issues/3500

**Comment by flashcode** [comment] 2023-04-07 17:13
The problem is going to be fixed in tmux and VTE, see:

- https://github.com/tmux/tmux/issues/3500
- https://gitlab.gnome.org/GNOME/vte/-/issues/2621

Therefore I close this issue as won't fix.

**Closed by flashcode** 2023-04-07 17:13 UTC
Labels: bug
