### ISSUE TITLE
socket fd not set on connect (FreeBSD 10.3-STABLE)

### ISSUE THREAD

**Issue by walker0643** [weechat/weechat#790] opened 2016-08-30 15:33 UTC
Problem 1:
Line 1470 in function network_connect_child_read_cb() in current git fails the following check on FreeBSD 10.3-STABLE:
  cmsg->cmsg_type == SCM_RIGHTS
which causes the socket fd to remain unset (-1).

Problem 2: 
Later on line 1609 the socket fd is pass onto the login/handshake callback without being validated; it's value is still -1. This causes the following error inside the client at runtime:
11:32:09  freenode  -- | irc: connecting to server irc.freenode.net/7000...
11:32:09  freenode  -- | irc: connected to irc.freenode.net/7000 (38.229.70.22)
11:32:09  freenode =!= | irc: sending data to server: error 9 Bad file descriptor

**Comment by flashcode** [comment] 2016-08-30 16:26
I can connect without any problem to IRC servers (SSL or not) on FreeBSD 10.3.
If someone knows the way to reproduce the problem, please tell me.

**Comment by walker0643** [comment] 2016-08-30 16:52
Several people have commented that vanilla FreeBSD 10.3 so perhaps try with FreeNAS 9.10 (which is FreeBSD 10.3-STABLE with a different configuration plus a web UI), then add a vanilla FreeBSD 10.3 jail and install weechat there.

**Comment by AnorexicSeal** [comment] 2016-09-13 05:20
Yeah i am having the same issues on freenas 9.10.
I installed through pkg.

**Comment by ephase** [comment] 2016-09-16 15:28
Hi,
So i have this issue in my weechat jail - FreeNAS 9.10 (FreeBSD 10.3)

**Comment by welwood08** [comment] 2016-10-07 08:28
I've been suffering from this for many months (had to switch to a different IRC client) and simply assumed it was a problem with my setup. I was hoping this would go away when weechat 1.4 was updated in FreeBSD ports, alas not.

For SSL servers (all I normally have configured), the problem manifests as follows:
```
irc: connecting to server irc.mozilla.org/6697 (SSL)...
irc: TLS handshake failed
irc: error: Error in the push function.
```

Testing a non-SSL connection produces the same `error 9 Bad file descriptor` as above. I'm also using FreeNAS 9.10 with a jail based off [the FreeBSD 10.3-RELEASE template](http://download.freenas.org/jails/10/x64/freenas-standard-10.3-RELEASE.tgz).

I've had `weechat.debug.irc` set to 32 since my last attempt to work out what was wrong, no useful information is revealed. Is there anything else to be done to help confirm the above diagnosis or otherwise usefully investigate this?

**Comment by masdeeper** [comment] 2017-01-07 02:37
I have the same problem in a fresh jail with FreeNAS-9.10.1-U4.

02:33:35 undernet  -- | irc: connecting to server irc.undernet.org/6667...
02:33:35 undernet  -- | irc: connected to irc.undernet.org/6667 (170.178.191.18)
02:33:35 undernet =!= | irc: sending data to server: error 9 Bad file descriptor

**Comment by walker0643** [comment] 2017-01-07 22:52
More info on the problem and a workaround...

INFO:

For some reason the kernel seems to be replacing the SCM_RIGHTS message (containing the new socket descriptor) with a useless SCM_CREDS message. Sample data dump follows...

**-- OUTGOING from child process that connects to the irc server --**
    hex data: outgoing msg
    00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00
    80 C4 FF FF FF 7F 00 00
    01 00 00 00 00 00 00 00
    90 C4 FF FF FF 7F 00 00
    18 00 00 00 00 00 00 00
    end hex data
    hex data: outgoing cmsg
    14 00 00 00 FF FF 00 00
    01 00 00 00 **<< 01 indicates an SCM_RIGHTS message**
    end hex data
    hex data: outgoing cmsg data
    30 73 72 00 **<< this is the socket fd**
    end hex data
     
**-- INCOMING to parent process that takes over the connection once it's established --**
    hex data: incoming msg
    00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00
    E0 E8 FF FF FF 7F 00 00
    01 00 00 00 00 00 00 00
    F0 E8 FF FF FF 7F 00 00
    18 00 00 00 20 00 00 00
    end hex data
    hex data: next incoming cmsg
    2C 00 00 00 FF FF 00 00
    03 00 00 00 **<< 03 indicates an SCM_CREDS message**
    end hex data
    hex data: next incomoing cmsg data
    60 6A F6 0A 08 00 00 00 **<< this is where the socket fd should be**
    00 00 00 00 0C 00 00 00
    00 00 00 00 00 00 00 00
    60 6A F6 0A 08 00 00 00
    end hex data

And so the connection fails because the parent never receives the socket descriptor.


WORKAROUND:

The workaround is to not use sendmsg()/recvmsg() at all. Weechat already has this workaround implemented, we just need to turn it on for FreeBSD....

```
diff --git a/src/core/wee-hook.c b/src/core/wee-hook.c
index 277f75388..e0dec95e8 100644
--- a/src/core/wee-hook.c
+++ b/src/core/wee-hook.c
@@ -117,7 +117,7 @@ hook_init ()
      */
     hook_socketpair_ok = 1;
 
-#if defined(__CYGWIN__) || defined(__APPLE__) || defined(__MACH__)
+#if defined(__CYGWIN__) || defined(__APPLE__) || defined(__MACH__) || defined(__FreeBSD__)
     hook_socketpair_ok = 0;
     (void) sock;
     (void) rc;

```

**Comment by welwood08** [comment] 2017-01-08 19:53
@walker0643 thank you very much! I have used that patch (with minor tweaks) to build weechat 1.6 from the FreeBSD ports tree and was immediately able to connect to both SSL and non-SSL servers (building without the patch still failed connections). Finally I can return home to weechat after so many months without it.

**Comment by walker0643** [comment] 2017-01-08 23:07
Turns out it's an issue in FreeNAS itself. I've created a PR there. Once it's fixed weechat should magically work again. Everyone that has used the patch above remember to undo it after FreeNAS fixes their end!

https://bugs.freenas.org/issues/20103

**Comment by masdeeper** [comment] 2017-01-08 23:12
The patch works for me as well. Thank you!

**Comment by walker0643** [comment] 2017-01-09 01:36
It seems FreeNAS is appending the SCM_CREDS message but it is still sending the SCM_RIGHTS message behind it. Unfortunately there is no way for the receiver to know this and looping on recvmsg() until you get the packet you're expecting won't work. Therefore I propose that the solution is just to expand the size of the receive buffer and allow for both messages.

This patch is better than the first as it allows us to keep using the better sendmsg() method rather than the more limiting bundle-of-sockets approach. It should also not interfere with any platforms on which this was never an issue. At this point I'm calling it fixed. Would you agree @flashcode ?

```
diff --git a/src/core/wee-network.c b/src/core/wee-network.c
index f5beb4f7f..f578e8e01 100644
--- a/src/core/wee-network.c
+++ b/src/core/wee-network.c
@@ -1402,7 +1402,10 @@ network_connect_child_read_cb (const void *pointer, void *data, int fd)
     int sock, i;
     struct msghdr msg;
     struct cmsghdr *cmsg;
-    char msg_buf[CMSG_SPACE(sizeof (sock))];
+    union {
+        char msg_buf[sizeof(struct cmsgcred) + CMSG_SPACE(sizeof (sock))];
+        struct cmsghdr align;
+    } u;
     struct iovec iov[1];
     char iov_data[1];
 
@@ -1452,8 +1455,8 @@ network_connect_child_read_cb (const void *pointer, void *data, int fd)
             {
                 /* receive the socket from the child process */
                 memset (&msg, 0, sizeof (msg));
-                msg.msg_control = msg_buf;
-                msg.msg_controllen = sizeof (msg_buf);
+                msg.msg_control = u.msg_buf;
+                msg.msg_controllen = sizeof (u.msg_buf);
 
                 /* recv 1 byte of data (not required on Linux, required by BSD/OSX) */
                 memset (iov, 0, sizeof (iov));
@@ -1464,13 +1467,15 @@ network_connect_child_read_cb (const void *pointer, void *data, int fd)
 
                 if (recvmsg (HOOK_CONNECT(hook_connect, child_recv), &msg, 0) >= 0)
                 {
-                    cmsg = CMSG_FIRSTHDR(&msg);
-                    if (cmsg != NULL
-                        && cmsg->cmsg_level == SOL_SOCKET
-                        && cmsg->cmsg_type == SCM_RIGHTS
-                        && cmsg->cmsg_len >= sizeof (sock))
+                    for (cmsg = CMSG_FIRSTHDR(&msg); cmsg != NULL; cmsg = CMSG_NXTHDR(&msg, cmsg))
                     {
-                        memcpy(&sock, CMSG_DATA(cmsg), sizeof (sock));
+                        if (cmsg->cmsg_level == SOL_SOCKET
+                            && cmsg->cmsg_type == SCM_RIGHTS
+                            && cmsg->cmsg_len >= sizeof (sock))
+                        {
+                            memcpy(&sock, CMSG_DATA(cmsg), sizeof (sock));
+                            break;
+                        }
                     }
                 }
             }
```

**Comment by welwood08** [comment] 2017-01-09 18:05
Confirming that replacing the previous workaround patch with the buffer patch also seems to work fine for both SSL and non-SSL connections on my system.

**Comment by flashcode** [comment] 2023-08-25 05:05
PR #885 has been closed, so I close this issue as well.
If you still have the issue today, please comment.

**Closed by flashcode** 2023-08-25 05:05 UTC
Labels: bug, not reproduced, help wanted
