### ISSUE TITLE
`paste_max_lines==0` not respected if `paste_bracketed==off`

### ISSUE THREAD

**Issue by adsr** [weechat/weechat#1977] opened 2023-07-06 03:26 UTC
## Bug summary

Hello, with the following config...

```
/set weechat.look.paste_max_lines 0
/set weechat.look.paste_bracketed off
```

...WeeChat behaves as if `paste_max_lines==1` on pasted input.  This appears to be implemented intentionally here:

https://github.com/weechat/weechat/blob/7b6c9328be81cc521db046ce706c36bc94cd3f5d/src/gui/gui-key.c#L2902-L2903

I tried simply deleting these lines which causes WeeChat to show a paste dialog for every single input, so I suspect the real fix would be in `gui_key_read_cb`.

## Steps to reproduce

1. Set above config
2. Copy "test\n" to clipboard and paste to a buffer

## Current behavior

Pasting "test\n" results in no Y/N dialog.

## Expected behavior

Pasting "test\n" results in Y/N dialog.

## Suggested solutions

I haven't stepped through the input handling code, but shouldn't it be possible to show the paste dialog for an input string like "test\n" even with bracketed paste disabled? I understand it's hard to differentiate a slow stdin vs a true paste without bracket sequences, but WeeChat seems to handle "test1\ntest2\n" so I'm unclear why "test\n" is different.

## Additional information

Somehow my config had `weechat.look.paste_bracketed==off` (I don't recall setting that but I may have :fish:) which led to an accidental "<sensitive_info>\n" paste slipping through today. I'm almost certain my v3.8 setup would have caught this as I make a lot of accidental pastes. I wonder if something in the upgrade process set `paste_bracketed=off` somehow. I see the default is `on` so I'm puzzled.

If this has affected anyone else, simply `/set weechat.look.paste_bracketed on` if your terminal supports it as it respects `paste_max_lines==0`.

---

- WeeChat version: 4.1.0-dev
- OS, distribution and version: Linux 6.2
- Terminal: xfce4-terminal
- Terminal multiplexer (screen/tmux/…/none): screen

**Comment by flashcode** [comment] 2023-07-06 09:34
Hi,
I configured both 3.8 and 4.0.0 with same config, I have the same behavior, did I miss something?

**Comment by trygveaa** [comment] 2023-07-06 09:49
I'm not able to reproduce this either.

> Somehow my config had `weechat.look.paste_bracketed==off` (I don't recall setting that but I may have ) which led to an accidental "<sensitive_info>\n" paste slipping through today.

Since 4.0.0 doesn't send anything automatically when you paste, it's only inserted into the input line, why is it a problem that you didn't get a paste confirmation?

**Comment by adsr** [comment] 2023-07-06 17:32
> Since 4.0.0 doesn't send anything automatically when you paste, it's only inserted into the input line, why is it a problem that you didn't get a paste confirmation?

This doesn't seem to be the behavior I get. Pasting "test\n" with the config above sends "test" to the buffer on 3.8 and 4.0.0.

> Hi, I configured both 3.8 and 4.0.0 with same config, I have the same behavior, did I miss something?

Yes that's right. This happens on 3.8 and 4.0.0 with completely default config + `paste_max_lines=0` + `paste_bracketed=off`. I'm puzzled how my old 3.8 setup used to prevent this. I use WeeChat everyday and paste frequently so I'm fairly certain the behavior used to be different in my old 3.8 setup, even though I'm struggling to reproduce the old behavior I remember. Is there another config setting that can impact this? (I already overwrote my config on 4 so I may have lost whatever config I had that was producing the old behavior.)

To clarify, the old behavior I remember was:

| on clipboard | paste effect |
| - | - |
| "test" | "test" goes into input box without Y/N dialog |
| "test\n" | Y/N dialog, send "test" to buffer if Y |
| "test1\ntest2\n" | same as above |

For now I have `paste_bracketed=on` which is slightly more strict than this in that it shows the Y/N dialog for "test" as well.

I will try again tonight to reproduce the old behavior. Either that or we will conclude I'm hallucinating :laughing:

**Comment by trygveaa** [comment] 2023-07-06 18:43
> This doesn't seem to be the behavior I get. Pasting "test\n" with the config above sends "test" to the buffer on 3.8 and 4.0.0.

Right, with paste_bracketed off it will be sent. I assume that's what you mean? With paste_bracketed on it should always just be put in the input line without being sent with 4.0.0.

I would recommend having it on, there's no reason to have it off afaik (I don't think it will cause problems even for terminal emulators that don't support bracketed paste, and most terminal emulators support it).

**Comment by adsr** [comment] 2023-07-06 19:40
> I would recommend having it on, there's no reason to have it off afaik (I don't think it will cause problems even for terminal emulators that don't support bracketed paste, and most terminal emulators support it).

Agree, I've enabled it. My only wish is that I could go back to no dialog for single-line pastes without a newline. This evening I'll try to figure out how that worked in my old 3.8 setup.

**Comment by trygveaa** [comment] 2023-07-06 20:17
I still struggle to understand why you need the confirmation prompt. Are you aware that you can press ctrl+_ to undo the paste?

**Comment by flashcode** [comment] 2023-07-07 06:55
@adsr: the new value for option `weechat.look.paste_max_lines` is 100, I recommend to use this value, so that any paste goes to the input (not sent to the buffer), and you can just press key Ctrl+_ if you don't want to send this.
This is the default behavior in 4.0.0 and then no need to confirm any more pastes in most cases.

**Comment by adsr** [comment] 2023-07-07 18:50
My config somehow got really messed up in the 3.8 -> 4 upgrade which was subtly breaking a bunch of stuff. For example:

```
[key]
b,a,c,k,space = "/input delete_previous_char"
ctrl-_ = "/input undo"
ctrl-a = "/input move_beginning_of_line"
ctrl-b = "/input move_previous_char"
ctrl-c,comma,_ = "/input insert \x1F"
ctrl-c,comma,b = "/input insert \x02"
ctrl-c,comma,c = "/input insert \x03"
ctrl-c,comma,i = "/input insert \x1D"
ctrl-c,comma,o = "/input insert \x0F"
ctrl-c,comma,v = "/input insert \x16"
ctrl-d = "/input delete_next_char"
ctrl-d,o,w,n = "/input history_global_next"
ctrl-e = "/input move_end_of_line"
ctrl-f = "/input move_next_char"
ctrl-f,1 = "/bar scroll buflist * -100%"
ctrl-f,1,1 = "/bar scroll nicklist * -100%"
ctrl-f,1,2 = "/bar scroll nicklist * +100%"
...
```

I started over with a fresh config and your comments are making a lot more sense now re: multi-line paste etc. 

Is this config thing a known bug or something worth digging into? For what it's worth I haven't started with a fresh config since v0.3.x.

**Comment by flashcode** [comment] 2023-07-07 19:23
This happens when you load a configuration of WeeChat 4.0.0+ in any older version (you must not do that, as new configs are not compatible any more with old releases).

To fix it, remove the key sections from weechat.conf and restart with version 4.0.0, all default keys will be created.

If if you had custom keys, restore a backup of old config if you have one.

**Comment by flashcode** [comment] 2023-07-13 06:49
I close this issue as this is the intended behavior.

**Closed by flashcode** 2023-07-13 06:49 UTC
Labels: bug, waiting info
