### ISSUE TITLE
Incorrect parsing of :trail in some numeric replies and messages

### ISSUE THREAD

**Issue by linuxdaemon** [weechat/weechat#1296] opened 2019-01-29 14:10 UTC
## Bug summary
Certain IRC numerics, such as RPL_TOPICTIME and RPL_INVITING, and messages such as MODE from the server may have a `:` before the last parameter. It appears weechat doesn't remove this properly, leading to a blank topic set time, an extra colon when setting modes and an extra colon when inviting a user.
`Mode ##channel [+o user :user2] by opuser`
`Nick has invited OtherNick to :#channel`

## Steps to Reproduce
1. Join `irc.irc.com/+6697`
2. Join an existing channel
3. Channel creation time and topic set time are blank

## Info
This seems to indicate a deeper issue with the parser, as according to RFC1459, <trail> should be treated the same as <middle> once the `:` is removed.

This was first noticed on `irc.irc.com` as we run InspIRCd v3 which adds a `:` before the last parameter for all server->client messages, which is valid according to the spec.

## Versions
- WeeChat version: 2.4-dev
- OS, distribution and version: Ubuntu 16.04

**Comment by flashcode** [comment] 2019-01-29 15:00
Hi,
I can not reproduce the issue with this server and a test channel.
Please paste here the content of the raw message received, as you can see it in `/server raw`

**Comment by linuxdaemon** [comment] 2019-01-29 15:15
```
09:09:02 --> irc.com :1.chimera.network.irc.com 332 Guest25001 ##ldtest :~-'* This topic requires snoonet
         premium to view *`-~
09:09:02 --> irc.com :1.chimera.network.irc.com 333 Guest25001 ##ldtest
         linuxdaemon!linuxdaemon@snoonet/staff/linuxdaemon :1547830882
```
Shows as 
```
09:09:02 -- Topic for ##ldtest is "~-'* This topic requires snoonet premium to view *`-~"
09:09:02 -- Topic set by linuxdaemon (linuxdaemon@snoonet/staff/linuxdaemon) on
```
```
09:09:04 <-- irc.com MODE ##ldtest
09:09:04 --> irc.com :1.chimera.network.irc.com 324 Guest25001 ##ldtest :+APnprst
09:09:04 --> irc.com :1.chimera.network.irc.com 329 Guest25001 ##ldtest :1465533502
```
shows as
```
09:09:02 -- Channel ##ldtest: 14 nicks (8 ops, 0 halfops, 0 voices, 6 normals)
09:09:04 -- Channel created on 
```
and
```
09:12:12 --> irc.com :1.chimera.network.irc.com 341 Guest25001 gonzobot :##ldtest
```
shows as
```
09:12:12 irc.com -- Guest25001 has invited gonzobot to :##ldtest
```

**Comment by flashcode** [comment] 2019-01-29 15:22
I checked in source, the colon is supposed to be automatically skipped by WeeChat (which is the case when I test).
It could maybe be caused by a script?
Can you try with a default config, without any script loaded?

**Comment by benharri** [comment] 2019-05-09 21:43
This is still happening in 2.4 and 2.5-dev when multiple modes are set.

Here's the raw line sent by inspircd 3.0.0
`:ChanServ!services@services.tilde.chat MODE #team +qo ben :ben`

It displays in weechat with the leading `:` for the last parameter
`Mode #team [+qo ben :ben] by ChanServ`

In this example, setting `-q` leaves the nick desynced and without the remaining `+o`.
`/names` can fix the desync in this case, but this line still isn't being properly parsed.

**Closed** 2019-05-10 19:02 UTC
Labels: bug, in progress
