### ISSUE TITLE
Set Relay Password command prints actual password to the weechat buffer

### ISSUE THREAD

**Issue by boywanders** [weechat/weechat#589] opened 2015-11-17 20:47 UTC
When executing the command /set relay.network.password yourpassword, yourpassword is obscured by asterisks. However, once executed, weechat will output the password in a message telling you that the password has been changed. I have created this issue as the output makes the initial attempt to obscure the password almost totally useless.

**Comment by boywanders** [comment] 2015-12-08 10:49
Update: It would appear that this bug is also found when inputting the password for a server via the /set command. e.g /set irc.server.example.password password obfusicates the password in the text input bar but when the return key is pressed the output will look like  Option changed: irc.server.example.password = "password"  (default: (undefined))

**Comment by Mikaela** [comment] 2015-12-08 11:12
I believe this is the expected behaviour of `/set` showing the current values. If you don't like passwords being visible there, you should take a look at `/help secure`.

@flashcode Why is this labeled as `bug` instead of closed with label of `invalid`?

**Comment by Spydar007** [comment] 2015-12-08 17:00
@Mikaela: because it isn't a invalid, he has already acknowledged that it is a bug.

**Comment by flashcode** [comment] 2015-12-10 06:42
@Mikaela: yes for me it's not very consistency to hide password in input, but display it once the option is set (even if you have workarounds like `/secure`).
That's why it's labelled bug, but it's almost a feature request, something missing to hide the passwords in options set.

**Comment by flashcode** [comment] 2019-10-06 11:59
Now all (or almost all) password options are evaluated, and then `/secure` can be used to store password, the passwords set with `/secure` are not displayed.
So I close this issue, as it would be hard to hide password in output of `/set` in a "smart" way.

**Closed by flashcode** 2019-10-06 11:59 UTC
Labels: bug
