### ISSUE TITLE
Confusing /query behavior

### ISSUE THREAD

**Issue by justinnoah** [weechat/weechat#274] opened 2014-12-09 18:09 UTC
Querying a nickname that starts with a channel type creates a situation where a nicklist is not shown, /part'ing does not work as expected in the buffer and basic IRC commands simply don't work as expected (unable to get nick lists, etc).

To leave the channel, one must switch to another buffer and run `/part #<channelname>`

**Comment by flashcode** [comment] 2015-01-24 15:57
I tried with version 1.1 and 1.2-dev, no problem with such query, I can easily close it with a `/part` on the buffer.
Do you still have the problem with 1.1 or devel version?

**Comment by flashcode** [comment] 2015-03-22 14:41
Some news about the problem? (see my question above)
Otherwise I'll just close the issue, because I'm unable to reproduce the problem.

**Comment by justinnoah** [comment] 2015-03-24 21:23
@flashcode let me check real quick...

**Comment by justinnoah** [comment] 2015-03-24 21:24
@flashcode Using 1.1.1, this is no longer an issue.

**Closed** 2015-03-25 21:00 UTC
Labels: bug, invalid
