### ISSUE TITLE
/ban, /unban, /quiet and /unquiet ignore MODES sent by server

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#576] opened 2015-11-05 12:36 UTC
freenode sends MODES=4, but WeeChat ignores it.

For example:

```
/ban Ciblia Euforia
2015-11-05 14:32:34+0200 [chanop] Affects (2): Mikaela(mikaela@unaffiliated/mikaela) Ciblia(Mikaela@unaffiliated/mikaela)
2015-11-05 14:32:34+0200 -- Mode ##Mikaela [+b *!*@*unaffiliated/mikaela] by Mikaela
2015-11-05 14:32:35+0200 [chanop] Affects (1): Euforia(mikaela@unaffiliated/mikaela/bot/dysforia)
2015-11-05 14:32:35+0200 -- Mode ##Mikaela [+b *!*@*unaffiliated/mikaela/bot/dysforia] by Mikaela
/unban Ciblia Euforia
2015-11-05 14:32:38+0200 -- Mode ##Mikaela [-b *!*@*unaffiliated/mikaela] by Mikaela
2015-11-05 14:32:38+0200 -- Mode ##Mikaela [-b *!*@*unaffiliated/mikaela/bot/dysforia] by Mikaela
```

What should have happened is WeeChat setting `+bb *!*@*unaffiliated/mikaela  *!*@*unaffiliated/mikaela/bot/dysforia` and `-bb *!*@*unaffiliated/mikaela  *!*@*unaffiliated/mikaela/bot/dysforia` instead and only went to next line if I was banning more than 4 users.

* Debian GNU/Linux 7.9 (wheezy)
* WeeChat 1.4-dev (git: v1.3-103-g99ebcca) Copyright (C) 2003-2015, compiled on Nov  5 2015 09:33:55

**Comment by Mikaela** [comment] 2015-11-05 13:02
Potential duplicate of https://github.com/weechat/weechat/issues/15 but I think this is more detailed.

**Comment by flashcode** [comment] 2015-11-07 09:10
Closing this one, duplicate of #15.
If needed, please complete the issue #15.

**Closed by flashcode** 2015-11-07 09:10 UTC

**Comment by Mikaela** [comment] 2015-11-07 09:13
Ok. I left it open as in some projects there is policy to label older bug as duplicate in case there is more detailed/clear newer one.

**Comment by flashcode** [comment] 2015-11-07 09:24
When possible, I prefer completing old bugs rather than opening a duplicate, even if more complete.

**Comment by Mikaela** [comment] 2015-11-07 09:34
The issue is that old bugs are hidden under all other bugs and depending on search terms they aren't encountered so easily.
