### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by jeffreyroberts** [weechat/weechat#1320] opened 2019-03-03 18:01 UTC
## Bug summary

configure: WARNING:
*** PHP (>=7.0) headers and/or libraries couldn't be found on your system.
*** Try to install libphp-embed with your software package manager.
*** WeeChat will be built without PHP support.
./configure: line 24144: syntax error near unexpected token `ENCHANT,'
./configure: line 24144: `        PKG_CHECK_MODULES(ENCHANT, enchant, ac_found_enchant_lib="yes", ac_found_enchant_lib="no")'
tmc@weaponsgrade:~/weechat$ dpkg -l | grep libphp-embed
ii  libphp-embed                     1:7.0+49                           all          HTML-embedded scripting language (Embedded SAPI library) (default)

## Steps to reproduce

1. clone
2. autogen.sh
3. configure

## Current behavior

configure breaks looking for libphp-embed

## Expected behavior

configure to work

## Suggested solutions

?

## Additional information

---

- WeeChat version: latest and greatest
- OS, distribution and version: debian 9 stretch

**Comment by weechatter** [comment] 2019-03-03 18:23
please try with cmake, its the recommended way to compile weechat:
https://weechat.org/files/doc/devel/weechat_user.en.html#compile_with_autotools

You can also use the binaries from https://weechat.org/download/debian/

**Comment by flashcode** [comment] 2019-08-10 07:45
Do you still have the problem? Please comment if that's the case.
I close the issue for now, not able to reproduce.

**Closed by flashcode** 2019-08-10 07:45 UTC
Labels: bug, waiting info
