### ISSUE TITLE
unicode emojis?

### ISSUE THREAD

**Issue by fuzzy76** [weechat/weechat#428] opened 2015-05-22 07:42 UTC
unicode emojis are filtered out. They display as blank spaces. The terminal handles them fine.

```
charset: terminal: UTF-8, internal: UTF-8
```

**Comment by Mikaela** [comment] 2015-05-22 07:44
Glib issue, duplicate of https://github.com/weechat/weechat/issues/79

**Comment by flashcode** [comment] 2015-05-22 18:04
Here's a post that could help you: https://blog.nytsoi.net/2015/05/04/emoji-support-for-weechat

**Closed by flashcode** 2015-05-22 18:04 UTC
