### ISSUE TITLE
weechat has unintended/accidental phone-home telemetry

### ISSUE THREAD

**Issue by sneak** [weechat/weechat#1548] opened 2020-08-02 01:41 UTC
## Bug summary

Weechat phones home on launch.

## Steps to reproduce

1. Launch weechat

<img width="670" alt="Screen Shot 2020-07-30 at 12 49 35" src="https://user-images.githubusercontent.com/408977/89113479-71202800-d426-11ea-9deb-c1987f828462.png">

## Current behavior

Connects to weechat.org.

## Expected behavior

Does not connect to the application developers, only to configured servers.

## Suggested solutions

Do not connect to weechat.org on launch.

- WeeChat version: 2.8
- OS, distribution and version: macOS, installed via nix

**Comment by sneak** [comment] 2020-08-02 01:41
I think this might be the cause:

https://github.com/weechat/weechat/blob/feb6258910d7fe907fddeea32e57f786079d82ec/src/plugins/script/script-config.c#L784

**Comment by flashcode** [comment] 2020-08-02 06:25
Hi,

This is not a bug but the expected behavior and this is not used at all for telemetry (there's no telemetry or usage report at all in WeeChat).

WeeChat is configured by default to use weechat.org reporitory to browse and install "official scripts" (as you can see on https://weechat.org/scripts).

If you run WeeChat with default config and without using the `/script` command, there should be no request made to weechat.org website (you can check with `weechat -t` which runs WeeChat in a temporary directory with default config).

Notes:

- Once the `/script` command has been used and the file "plugins.xml.gz" downloaded at least one time, there's an automatic refresh on this file periodically, so requests to weechat.org can be made on next startup if the content is considered obsolete.
- If you manually remove the file `~/.weechat/script/plugins.xml.gz`, then the script plugin should now try to download any more the file `plugins.xml.gz`.

**Comment by sneak** [comment] 2020-08-02 07:22
Whether it is *used* for telemetry or not is immaterial.  The HTTP request itself *is* a telemetry event, even if you did not intend it as such.  Whether you keep the web logs or delete them is irrelevant to the bug.

The client should not make any requests to the developers without opt in consent of the user, otherwise it *could* be used to track users of the program, *regardless of whether you are presently using it as telemetry or not*.

You have to obtain opt-in consent before phoning home, otherwise it's embedded spyware.

**Comment by flashcode** [comment] 2020-08-02 07:53
Sure I understand what you mean.

As I said, this is done only with an explicit user action. If you don't use the `/script` command, the request is never done (if ever it is, this is a bug that should be fixed).

Moreover, if you don't want to use this plugin (the script manager), you can disable on build:

    cmake .. -DENABLE_SCRIPT=OFF

I think this is the same behavior as other programs like browsers: when you want to search a plugin, you'll make requests to their "store" and download files from there if you install one. Like in WeeChat, this is done on a user action as well, but you don't have to enable something specific in the browser to allow it to make requests to its store.

Am I missing something else?

**Comment by flashcode** [comment] 2020-09-02 17:21
I noticed one thing: when the script plugin is loading (so for example on WeeChat startup), the file "plugins.xml.gz" is updated if it's too old, if ever you have run at least one time the `/script` command in past (ie if the file "plugins.xml.gz" is present on disk).

This automatic download on startup can be removed because the file would be downloaded again on any `/script` action.

I'll remove this automatic download and close this issue, as now any download will be really performed on user action only.

**Comment by sneak** [comment] 2020-09-03 15:41
That’s a step in the right direction, but I don’t think it’s good enough.  There is nothing to indicate that running `/script` is going to leak to my ISP, national military, and you that my IP address is a weechat user.

Such inadvertent telemetry like this should be opt-in.  Running `/script` without opting in should print a message that says “To use this command WeeChat needs to contact WeeChat servers to download metadata, which is prevented by default to protect your privacy.  To opt in to these metadata updates, please run /set whatever_setting true and then try /script again, and be aware that WeeChat may contact the metadata server periodically to fetch updates.”

It’s no more reasonable to automatically phone-home for /script without a warning or opt in than it is for /msg.

**Closed** 2020-09-06 17:16 UTC
Labels: bug

**Comment by flashcode** [comment] 2020-09-06 17:17
Done.

To enable any download (list of script or a script): `/set script.scripts.download_enabled on` (required on a new install and after upgrade from an old version).

**Comment by sneak** [comment] 2020-09-06 17:19
You're awesome!  Thank you so much.  👍

**Comment by F8ER** [comment] 2020-10-04 05:23
I agree. The WeeChat is purely magnificent application with awesome community.
Even the fact of @flashcode actually listened to this issue and you, @sneak even after reclarifying, really matters.
Thank you very much for improving it, dear @flashcode ... really ...
