### ISSUE TITLE
Cannot see or type the unicode character 💩

### ISSUE THREAD

**Issue by rbarlow** [weechat/weechat#460] opened 2015-07-09 19:05 UTC
Humorously, I learned today that I cannot receive the unicode character 💩 (1F4A9). When someone sent this character to me, it appeared on my end as a single ASCII space character (code point 32). Similarly, if I type this character into weechat, I see a single space. Interestingly, if I send the message, the person on the other end does receive 💩.

My terminal emulator does support this character.

This is weechat 1.0.1 from EPEL, though I also confirmed the issue on 1.1.1 from Gentoo.

My client does seem to support many other unicode characters, including ☺ and ☃ so I believe support for unicode is otherwise working.

**Comment by Mikaela** [comment] 2015-07-09 20:39
Duplicate of https://github.com/weechat/weechat/issues/79

**Comment by flashcode** [comment] 2015-07-10 05:35
If you can see the char in bare display (alt-L), then yes I think it's a duplicate of #79.
See the FAQ for more info: https://weechat.org/doc/faq#unicode_chars

**Comment by Mikaela** [comment] 2015-07-10 05:58
I believe this character is affected by #79 and keep in mind that if you use mosh or something else that uses the same glibc, you won't see the character even in bare mode.

**Comment by rbarlow** [comment] 2015-07-10 16:32
@flashcode I can see the 💩 in bare display mode. Thanks for pointing that mode out, it makes clicking links much easier!

**Closed** 2015-07-10 17:23 UTC
Labels: bug, duplicate

**Comment by flashcode** [comment] 2015-07-10 17:25
You're welcome.
I added this bare display for click on long URLs (without having to use scripts).
