### ISSUE TITLE
Weechat 3.4 hangs forever when TERM=xterm-direct

### ISSUE THREAD

**Issue by nickbp** [weechat/weechat#1755] opened 2022-02-23 07:12 UTC
## Bug summary

If weechat is started with `TERM=xterm-direct`, it will immediately hang forever, showing a black screen while using lots of CPU. It will only get out of this state by using SIGTERM. At first I thought it was a bad build - I wasn't able to figure out the problem until attaching gdb to a hung instance of weechat (stacktrace below) and then finding mention in feature ticket #1364 of someone else seeing similar behavior circa 2019.

I use `xterm-direct` in order to get full color in terminal Emacs, which supports it.

## Steps to reproduce

1. Run weechat as follows:
```
$ TERM=xterm-direct weechat
```

## Current behavior

Weechat will immediately enter the hung state with 100% CPU usage. It will only exit with e.g. `killall -9 weechat` (SIGTERM isn't enough).

## Expected behavior

weechat will start without instantly hanging forever.

## Suggested solutions

#1364 (from Jun 2019) implies that >256 colors are not supported in weechat today. But maybe in the meantime it could treat `xterm-direct` as equivalent to `xterm-256color` to avoid entering this state?

## Additional information

I am able to work around the problem by assigning the following alias in `~/.bashrc`:
```
alias weechat='TERM=xterm-256color /usr/bin/weechat'
```

gdb stacktrace of the pid when in the hung state:
```
#0  0x00007febbd02063e in __strcmp_avx2 () from /usr/lib/libc.so.6
#1  0x000055a69134336d in weelist_insert ()
#2  0x000055a6913434e3 in weelist_add ()
#3  0x000055a691396c99 in gui_color_palette_build_aliases ()
#4  0x000055a6913998e1 in gui_main_init ()
#5  0x000055a691316e93 in weechat_init ()
#6  0x000055a691316076 in main ()
```

---

- WeeChat version: 3.4
- OS, distribution and version: Arch Linux (rolling release)
- Terminal: gnome-terminal (with `TERM=xterm-direct` configured in `~/.bashrc` for aforementioned use in Emacs)
- Terminal multiplexer (screen/tmux/…/none): none

**Comment by nickbp** [comment] 2022-02-23 07:13
Going by [this commit](https://github.com/toshokan/dotfiles/commit/b1c0c11b1531155e2197efcfc7fe1c53630fd01a) referenced in #1364, looks like someone else is seeing the same issue in zsh.

**Comment by flashcode** [comment] 2022-02-23 09:15
Hi,

Thanks for your report, I think this is a duplicate of #1701.
If you confirm, I'll mark this issue as duplicate.

And I'll try to investigate soon this problem.

**Comment by nickbp** [comment] 2022-02-23 09:24
Yes that looks like the same root problem, feel free to mark as a duplicate. Thanks!

**Closed** 2022-02-23 09:29 UTC
Labels: bug, duplicate
