### ISSUE TITLE
Allow irc.network.lag_reconnect to be set per-server

### ISSUE THREAD

**Issue by github-cygwin** [weechat/weechat#1041] opened 2017-07-24 08:24 UTC
This is a feature request.

I think this setting makes sense to be set to a non-0 value by default.  However,
certain IRC gateways to proprietary services (Slack, here's looking at you) don't
reply to pings, thus the non-0 irc.network.lag_reconnect disconnects and reconnects
weechat every couple of minutes.

In theory it would be nice to have two such settings:
```
irc.network.lag_reconnect = 300
irc.server.<Servername>.lag_reconnect = 0
```
Thanks,
Corinna

**Comment by flashcode** [comment] 2017-07-24 08:33
Hi,
This is a duplicate of #46.
Moving the option in server will by default use 2 values: one in "server_default" category, and one in each server (inheriting the option from "server_default" if not set).

**Closed by flashcode** 2017-07-24 08:33 UTC
Labels: duplicate, enhancement
