### ISSUE TITLE
allow spaces surrounding the ";" command separator

### ISSUE THREAD

**Issue by highflyer77** [weechat/weechat#550] opened 2015-10-12 19:03 UTC
this seems to be a bug
certain commands will not accept a space after the ; command separator

> 18:00:55        <Petzku>  Can someone tell me why this isn't working? (cron.py)
> 18:00:58\*       0 0 \* \* \* \* core.weechat commands /mute save; /print -core saved
> 18:01:42         it does save, but instead of printing "saved" in the core buffer, it prints "=!= |
>                        You can not write text in this buffer"
> ...
> 18:06:01\*    <singalaut>  I don't use cron.py but try remove the space after ;
> 18:06:31        <Petzku>  singalaut: thanks, that worked

WeeChat doesn't seem to give an error to the real cause either.
I too have had this happen working with an alias once.
When I figure out which one that was I'll send you an update here.

Thanks

**Comment by flashcode** [comment] 2015-10-12 19:10
Here the command is split and executed by script cron.py, not WeeChat, so the issue is in the script.
So:
1. please open a bug in the scripts repository for cron.py
2. if you find similar problem in WeeChat itself, please add it to this issue, otherwise I'll just close it.

**Comment by highflyer77** [comment] 2015-10-12 20:04
I can not find the same issue that I had once (using aliases), but I do not use the cron.py script.  So I know that it was not that. If I bump into it again, I'll re-open the issue.
Therefore, I am closing this one.

**Comment by highflyer77** [comment] 2015-11-02 00:38
Found it again but seems to be the opposite effect,

>   squirrel>  say uh. i wrote /part;/join, and weechat put that in the chat. why
>   squirrel>   /part;/join
>   squirrel>   see it did it again!
>  t3chguy>  squirrel: you may have a script or trigger that prevents accidental / stuff
>   squirrel>  t3chguy: you try typing that
>  t3chguy>  I'm on w-a, not sure what buffer is actually selected xD
>   squirrel>  hee
>strayPuppy>  seems to work with a space after /part
>    squirrel>  i just tried on a weechat -d and it still puts stuff in channel
> mumixam>  /part;/join
> mumixam>  confirmed

Should work with or without whitespace,
maybe should change the title?

Thanks

**Comment by flashcode** [comment] 2015-11-02 13:51
Same problem as #570 ?
If yes, I'll just close this one. Otherwise please explain me the diff with the other issue.

**Comment by flashcode** [comment] 2017-06-12 19:42
Closing old issue.

**Closed by flashcode** 2017-06-12 19:42 UTC
Labels: bug
