### ISSUE TITLE
Perl plugins crash on weechat::hook_process_hashtable calling https URLs

### ISSUE THREAD

**Issue by Lalufu** [weechat/weechat#1044] opened 2017-07-27 08:57 UTC
Calling weechat::hook_process_hashtable() from a perl plugin while using "url:https://..." as the command name results in a crash and a backtrace. I'll attach logs and a test plugin to reproduce.

Crash log:
[weechat_crash_20170727_5831.log.txt](https://github.com/weechat/weechat/files/1179358/weechat_crash_20170727_5831.log.txt)

Test plugin:
[test.pl.txt](https://github.com/weechat/weechat/files/1179362/test.pl.txt)

Load the plugin (/script load test.pl), then use "/test_url" to trigger the issue.

This is weechat 1.9 on fedora 25.

**Comment by Lalufu** [comment] 2017-07-27 09:12
Installing debuginfo packages to get a more useful backtrace makes the problem go away it seems.

**Comment by flashcode** [comment] 2017-07-30 07:08
Hi,
After tests with your script, I can not reproduce the crash.
If you can't get a backtrace and if noone else can reproduce, I'll have to close the issue.

**Comment by weechatter** [comment] 2017-07-30 11:49
works for me as expected. no crash. Tested with:
perl: 5.24.1
perl: 5.22.1

**Comment by Lalufu** [comment] 2017-07-30 14:13
On Sun, Jul 30, 2017 at 12:09:01AM -0700, Sébastien Helleu wrote:
> Hi,
> After tests with your script, I can not reproduce the crash.
> If you can't get a backtrace and if noone else can reproduce, I'll have to close the issue.

This seems to require more a more complicated trigger condition.
As mentioned before I was not able to trigger the traceback
with debug symbols installed, and even after removing the symbols
again I still cannot trigger the crash any more.

I'll see if I can somehow figure out how to make this happen, until
then you can close this.

**Comment by flashcode** [comment] 2019-02-25 23:04
Not reproduced, closing the issue.

**Closed by flashcode** 2019-02-25 23:04 UTC
Labels: bug, not reproduced
