### ISSUE TITLE
Crash when exiting

### ISSUE THREAD

**Issue by stacyharper** [weechat/weechat#2142] opened 2024-07-03 09:41 UTC
### Describe the bug

From some weeks (maybe months), Weechat is crashing everytime I close it. I noticed this on multiple of my machines.

### Steps to reproduce

Just `/quit`

### Current behavior

```
*** Very bad! WeeChat is crashing (SIGSEGV received)
*** Full crash dump was saved to /home/stacy/.local/state/weechat/weechat_crash_20240703_24246.log file.
***
*** Please help WeeChat developers to fix this bug:
***
***   1. If you have a core file, please run: gdb /path/to/weechat core
***      then issue command: "bt full" and send result to developers.
***      See the user's guide for more info about enabling the core files
***      and reporting crashes:
***      https://weechat.org/doc/weechat/stable/user/#report_crashes
***
***   2. Otherwise send the backtrace (below), only if it is a complete trace.
***      Keep the crash log file, just in case developers ask you some info
***      (be careful, private info like passwords may be in this file).

======= WeeChat backtrace =======
(written by WeeChat 4.3.3, compiled on Jun 23 2024 17:41:36)
  No backtrace info (no debug info available or no backtrace possible on your system).
======= End of  backtrace =======
Aborted
```

Log: https://paste.sr.ht/~stacyharper/600cd136a0d40e60d8fd3cd8067ab099c5614634

### Expected behavior

Close with respects

### Additional information

My weechat configuration can be found in my dotfiles:

https://git.sr.ht/~stacyharper/dotfiles/tree/master/item/.config/weechat

### WeeChat version

4.3.3

### What OS/distribution are you using?

Alpine Linux

### On which terminal are you running WeeChat?

Foot

### Which terminal multiplexer are you using?

none

**Comment by flashcode** [comment] 2024-07-03 11:07
Hi,

This could be to the bug in Python 3.12, are you using this version of Python with multiple Python scripts loaded in WeeChat?

If yes, please try to compile either the branch 4.3 (future version 4.3.4) or master (future version 4.4.0 with new features)?

The bug is not yet fixed on Python side, but there's a workaround in WeeChat that should prevent the crash on `/quit`.

See issue #2046 and PR #2126.

**Comment by trygveaa** [comment] 2024-07-03 12:08
I checked with alpine now. I get the same crash with v4.3.3, but no crash in master or the 4.3 branch, so the workaround works there.

Can't say for sure this is the issue you're experiencing since Alpine annoyingly doesn't have standard backtraces, but it's very likely.

**Comment by flashcode** [comment] 2024-07-03 12:17
Thanks, I'll then release version 4.3.4 as soon as possible.

**Comment by flashcode** [comment] 2024-07-03 12:44
I close as duplicate of #2046.

**Closed by flashcode** 2024-07-03 12:44 UTC
Labels: bug, waiting info
