### ISSUE TITLE
WeeChat freezes while notify-send is run before user login

### ISSUE THREAD

**Issue by cmyster** [weechat/weechat#1443] opened 2020-01-22 10:42 UTC
## Bug summary
If I did not login to my desktop (xfce4 with lightdm) and weechat is set to send a notification for alerts with notify-send, then notify-send will get stuck and weechat will get stuck. I can't enter any key.
I can overcome it by killing notify-send, but each time its fired weechat becomes stuck again.

## Steps to reproduce
Setup:
PC_A has ssh, PC_B has weechat, tmux, xfce4 and lightdm and is currently turned off.
weechat is configured to use send-notify on alerts.
1. Turn on PC_B but do not log in.
2. From PC_A ssh to PC_B.
3. Start tmux.
4. Start weechat.
5. Receive an alert.

## Current behavior
weechat is unresponsive.
notify-send is working in the background.

## Expected behavior
weechat should not be stuck if notify-send is.

## Suggested solutions
Something with ./weechat_fifo ?

## Additional information
uname -rpm
5.4.13-gentoo x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

Data from Gentoo's EIX:
net-irc/weechat
     Installed versions:  2.7-r1.
     Compiled at: 05:54:22 PM 12/31/2019.
     Compiled with support for (alias buflist charset exec fifo fset irc logger nls perl python relay scripts spell ssl trigger xfer).
     Compiled without (doc guile lua man php ruby tcl test).

---

- WeeChat version: 2.7-r1
- OS, distribution and version: 5.4.13-gentoo x86_64

**Comment by flashcode** [comment] 2020-01-22 11:55
WeeChat is single-threaded, so if a script, trigger or something is using notify-send, it must be done in background (for example with the hook_process API function). Same for any blocking action like a network call.
WeeChat itself does not run blocking command without a forked process by default, so I close this issue, the problem is not in WeeChat itself.

**Closed by flashcode** 2020-01-22 11:55 UTC
Labels: bug
