### ISSUE TITLE
mIRC colour code rendering works inconsistently and doesn't support the "blinking" tag

### ISSUE THREAD

**Issue by brndd** [weechat/weechat#943] opened 2017-04-06 16:10 UTC
Recently, when porting over the famous /saluto alias by pipe/nature/#adom, used by dozens of people all around IRCnet since 2005, I noticed that the mIRC colour rendering works inconsistently, and also works differently from at least irssi.

Here is the alias I'm using as it appears in alias.conf:
`saluto = "/say ^B^_^C0,3Un Grosso Sal^V^C15,15uto al Mio Mi^V^C0,5gliore Amico  ^V^C15,1< $1 >"`

Here's the irssi version of the alias:
`saluto = "say \\002\\037\\0030,3Un Grosso Sal\\026\\00315,15uto al Mio Mi\\026\\0030,5gliore Amico  \\006\\026\\00315,1< $0 >";`

Here \\002 is the bold character, \\037 is the underline character, \\003 is the colour character, \\026 is the "reverse" character and \\006 is the "blink" character.

The first issue with this is that when I query myself and use this alias, it appears differently on the sending end than it does on the receiving end:
![saluto](http://i.imgur.com/8S7mnAt.png)

The second issue is that Weechat doesn't support the "blinking" control character, represented by the ASCII character 6 (^F). This character is rendered as a space when Weechat sees it, and it has no effect on the appearance of text.

I'm not sure what clients actually support this feature, but in irssi it seems to cause the background colour to become brighter using some mysterious irssi logic. Here's an example of a bunch of different colour combinations without and with the ^F character:
![irssi](http://i.imgur.com/zpX3ZuO.png)

**Comment by pipatron** [comment] 2017-04-06 16:14
This is a pretty important issue. I hope the developers take this blatant discrepancy seriously. I was going to convert from irssi to weechat just this evening, but after seeing this report, I no longer feel that I can trust that I get the same user experience that I'm used to.

**Comment by flashcode** [comment] 2017-04-06 18:35
The blinking attribute is currently not supported in WeeChat, do you have any link on this attribute? Is this something standard? (I can't find any docs on that)

**Comment by brndd** [comment] 2017-04-06 19:05
https://github.com/irssi/irssi/blob/master/docs/formats.txt Here's some link on it. It might be an irssi feature. HexChat, for instance, does not support the character either.

**Comment by arza-zara** [comment] 2017-04-07 10:21
The inconsistencies are in 1. same color in foreground and background + reverse, 2. reverse in /say:
```
/eval aaa${\x03}3,3aaa${\x16}aaa
/eval /say aaa${\x03}3,3aaa${\x16}aaa
```
![bug-ss](http://weechat.arza.us/mirccolor-bug.png)
\026 in /say always makes bold instead of reverse:
```
/eval /say aaa${\x16}aaa
```
![bug-ss2](http://weechat.arza.us/mirccolor-bug2.png)

**Comment by flashcode** [comment] 2017-04-07 11:59
I found the bug with the difference on the reverse attribute displayed between the two messages, it's caused by a double color decoding. I'll fix that very soon.

For the "blink" attribute, I'm not sure if something specific to irssi should be added, this is not something standard and widely used for me. If someone thinks it should really be added, please comment on this issue.

**Comment by brndd** [comment] 2017-04-07 12:14
The blink attribute probably doesn't need to be supported as frankly it seems at best useless and at worst very irritating. It might be useful to hide the character from messages that contain it, though. It uses ASCII character 6, ["ACK"](https://en.wikipedia.org/wiki/Acknowledgement_(data_networks)).

**Comment by nyuszika7h** [comment] 2017-04-08 21:22
Agreed with @brndd, I consider not supporting blinking a feature.

**Comment by flashcode** [comment] 2017-04-09 05:34
Currently all control chars (ASCII code < 32 except Tabs) are displayed with just one space on screen when they are found in a message.
So there's no special case for the char 6.

**Comment by yunginnanet** [comment] 2020-12-23 23:15
**Make IRC blinky again.**

**Comment by flashcode** [comment] 2023-08-28 07:04
Blink attribute was added in version 3.8 via #1855.
I close this issue, if there are other remaining issues, please comment here.

**Closed by flashcode** 2023-08-28 07:04 UTC
Labels: feature
