### ISSUE TITLE
Nick highlight triggers incorrectly on nickname followed by accented characters. 

### ISSUE THREAD

**Issue by Cronnix** [weechat/weechat#644] opened 2016-01-04 12:27 UTC
Happens when you nick something like "Rob", and another person types "Robå" as part of a sentence, which will incorrectly trigger nick highlight. Does not trigger on "Roba", only when someone types your nick followed by accented character. 

This mostly occurs for users that nick something short that may be used in a word together with accented characters afterwards. I nick "N" on a network, which fires off highlights every few minutes for scandinavic languages when people typ "någonting", "nää", "snål", etc.

**Comment by sim642** [comment] 2016-01-04 13:02
What locale settings does the terminal running WeeChat have (output of `locale` from the terminal)?

Apparently @weechatter can reproduce the issue and uses `de_DE.UTF-8`, while I have a mix of `en_US.UTF-8` and `et_EE.UTF-8` and am unaffected by this issue.

**Comment by Cronnix** [comment] 2016-01-04 13:10
I'm on "en_US.UTF-8" while being located in Sweden.

**Comment by flashcode** [comment] 2016-01-04 20:06
Does this happen with default configuration and no script loaded? (you can try `weechat --dir /tmp/weechat`).

**Comment by Cronnix** [comment] 2016-01-12 16:22
Was away on holidays, sorry. Yes, this still happens when running weechat with the above command.

**Comment by flashcode** [comment] 2016-01-13 07:05
I'm not able to reproduce the problem.
Could you please give me the exact steps (with a new config) to reproduce the problem?
Which nick are you using, and which message received triggers highlight and should not?

**Comment by Cronnix** [comment] 2016-01-13 09:54
This applies to any nick running the default config. Any message containing your nick as a part of the word, followed by the accented characters such as "ÅÖÄ", incorrectly triggers the highlight. 

So if I nick "Cronnix", and someone types "Cronnixå", it triggers highlight for me in wechat but not in other clients. This causes issues when using a nick that would commonly be part of a longer word. 

This doesn't occur when the nick is followed by english letters such as "A", so "Cronnixa" will not trigger highlight, only accented letters will. I checked with someone in #weechat channel, they seems to be able to reproduce the issue. Also tried with both terminal and iTerm, this happens in both. 

In my case, I started nicking simply "N", and in weechat any word containing capital N followed by accented letter, such as "Nästan", triggered highlights.

**Comment by flashcode** [comment] 2016-01-13 15:04
Your options weechat.look.highlight and weechat.look.highlight_regex are empty (which is default)?
I'm still not able to reproduce at all...

**Comment by Cronnix** [comment] 2016-01-18 13:55
No weird options in highlight settings, checked that in #weechat help channel before when I stopped by there. Afaik someone was able to reproduce it there so I dont think it's me only.

**Comment by flashcode** [comment] 2016-01-18 20:10
Yes, @weechatter was able to reproduce, but only once, and he's not able to reproduce now.
So without being able to reproduce, for now I cannot fix that...

**Comment by flashcode** [comment] 2019-06-16 18:27
Not reproduced, closing the issue.

**Closed by flashcode** 2019-06-16 18:27 UTC
Labels: bug, not reproduced, waiting info
