### ISSUE TITLE
U+20Dx followed by a space truncates text 

### ISSUE THREAD

**Issue by andriesgroen** [weechat/weechat#289] opened 2014-12-31 07:12 UTC
Characters in the U+20D0 - U+20DF range followed by a space will make the rest of the text disappear.
This can be replicated by doing `/input insert Hi \u20d2 Test`.
Input
![penisss2](https://cloud.githubusercontent.com/assets/3038882/5586171/666a736c-9092-11e4-95d7-bacbd22849d2.png)
Output
![penisss](https://cloud.githubusercontent.com/assets/3038882/5586166/3df9acb8-9092-11e4-85b7-9295e7bfda6a.png)

**Comment by nyuszika7h** [comment] 2015-04-05 12:42
Also reproduced with U+202D LEFT-TO-RIGHT OVERRIDE.

**Comment by nyuszika7h** [comment] 2015-07-29 11:26
Seems to be fixed now.

```
WeeChat 1.3-dev (git: v1.2-129-g784ba4e) [compiled on Jul 27 2015 18:02:44]
```

**Comment by flashcode** [comment] 2015-07-29 21:08
@nyuszika7h : the bug is still there for me.
Which config are you using? (OS, terminal, ...)

**Comment by nyuszika7h** [comment] 2015-07-30 11:21
Sorry, I was testing wrong, I forgot that it doesn't work when the character is at the beginning of the line.

**Comment by mquin** [comment] 2017-09-09 18:31
I've encountered what I think is a related problem with U+200E LEFT-TO-RIGHT mar.  If encountered in an incoming message will break positioning of the nicklist and cause scrambling elsewhere on the screen.

**Comment by flashcode** [comment] 2020-05-09 17:53
It's working fine for me with WeeChat 2.9-dev (git: v2.8-130-gf987e445e), using glibc 2.30.

The command `/input insert Hi \u20d2 Test` inserts this text in input:

    Hi ⃒ Test

So I close the issue, please comment if the problem is still there.

**Closed by flashcode** 2020-05-09 17:53 UTC
Labels: bug
