### ISSUE TITLE
If a relay is only partially synchronized, renaming a buffer causes new lines not to be delivered to the relay

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#1428] opened 2019-11-18 18:29 UTC
## Bug summary

if a relay is only partially synchronized (`sync * buffers,upgrade`), when a user changes their nickname, thus changing the full name of the buffer, new messages stop arriving to the relay. happens if a relay is using pointers to synchronize. `desync`/`sync` on the same pointer solves the issue.

fully synchronized relays are not affected.

## Steps to reproduce

here's a full transcript sans the ping/pong messages

relay connects

    18:07:56 --> [1] weechat | init password=hunter2,compression=zlib
    18:07:56                 | (version) info version_number
    18:07:56 <-- [1] weechat | obj: 49 bytes, id: version
    18:07:56 --> [1] weechat | (listbuffers) hdata buffer:gui_buffers(*)
                             | number,full_name,short_name,type,title,nicklist,local_variables,notify,hidden
    18:07:56 <-- [1] weechat | obj: 986/2485 bytes (61%, 0.58ms), id: listbuffers
    18:07:56 --> [1] weechat | (last_read_lines) hdata buffer:gui_buffers(*)/own_lines/last_read_line/data buffer
    18:07:56                 | (hotlist) hdata hotlist:gui_hotlist(*) buffer,count
    18:07:56                 | sync * buffers,upgrade
    18:07:56 <-- [1] weechat | obj: 145/236 bytes (39%, 0.14ms), id: last_read_lines
    18:07:56 <-- [1] weechat | obj: 114/175 bytes (35%, 0.13ms), id: hotlist

i open buffers, 0x151ab58 is a channel with bob in it, and 0x1594600 is a query with bob

    18:08:52 --> [1] weechat | sync 0x151ab58
    18:08:52 --> [1] weechat | (last_read_lines) hdata buffer:gui_buffers(*)/own_lines/last_read_line/data buffer
    18:08:52                 | (hotlist) hdata hotlist:gui_hotlist(*) buffer,count
    18:08:52 <-- [1] weechat | obj: 145/236 bytes (39%, 0.25ms), id: last_read_lines
    18:08:52 <-- [1] weechat | obj: 115/175 bytes (35%, 0.23ms), id: hotlist
    18:08:52 --> [1] weechat | (29) hdata buffer:0x151ab58/own_lines/last_line(-200)/data
                             | date,displayed,prefix,message,highlight,notify,tags_array
    18:08:52 <-- [1] weechat | obj: 4267/28194 bytes (85%, 2.83ms), id: 29
    18:08:52 --> [1] weechat | (nicklist) nicklist 0x151ab58
    18:08:52 <-- [1] weechat | obj: 256/567 bytes (55%, 0.19ms), id: nicklist

    18:08:55 --> [1] weechat | sync 0x1594600
    18:08:55 --> [1] weechat | (last_read_lines) hdata buffer:gui_buffers(*)/own_lines/last_read_line/data buffer
    18:08:55                 | (hotlist) hdata hotlist:gui_hotlist(*) buffer,count
    18:08:55                 | (30) hdata buffer:0x1594600/own_lines/last_line(-200)/data
                             | date,displayed,prefix,message,highlight,notify,tags_array
    18:08:55                 | (nicklist) nicklist 0x1594600
    18:08:55 <-- [1] weechat | obj: 145/236 bytes (39%, 0.24ms), id: last_read_lines
    18:08:55 <-- [1] weechat | obj: 115/175 bytes (35%, 0.21ms), id: hotlist
    18:08:55 <-- [1] weechat | obj: 554/2224 bytes (76%, 0.57ms), id: 30
    18:08:55 <-- [1] weechat | obj: 131/172 bytes (24%, 0.22ms), id: nicklist

bob sends me a pm

    18:09:38 <-- [1] weechat | obj: 250/354 bytes (30%, 0.18ms), id: _buffer_line_added

    18:09:44 <-- [1] weechat | obj: 247/366 bytes (33%, 0.18ms), id: _buffer_localvar_added

bob changes nick (note: there's two `_buffer_renamed` due to buffer's full name and short name being changed separately)

    18:10:20 <-- [1] weechat | obj: 263/379 bytes (31%, 0.18ms), id: _buffer_line_added
    18:10:20 <-- [1] weechat | obj: 231/315 bytes (27%, 0.17ms), id: _buffer_localvar_changed
    18:10:20 <-- [1] weechat | obj: 234/331 bytes (30%, 0.17ms), id: _buffer_renamed
    18:10:20 <-- [1] weechat | obj: 234/331 bytes (30%, 0.15ms), id: _buffer_renamed
    18:10:20 <-- [1] weechat | obj: 228/315 bytes (28%, 0.16ms), id: _buffer_localvar_changed
    18:10:20 <-- [1] weechat | obj: 205/342 bytes (41%, 0.17ms), id: _nicklist_diff
    
    18:10:45 <-- [1] weechat | obj: 249/368 bytes (33%, 0.18ms), id: _buffer_localvar_changed
    18:10:46 <-- [1] weechat | obj: 249/368 bytes (33%, 0.18ms), id: _buffer_localvar_changed

bob sends me a pm

    💥 nothing gets received 💥

i open and close the buffer in the relay client

    18:11:14 --> [1] weechat | desync 0x1594600

    18:11:19 --> [1] weechat | sync 0x1594600
    18:11:19 --> [1] weechat | (last_read_lines) hdata buffer:gui_buffers(*)/own_lines/last_read_line/data buffer
    18:11:19                 | (hotlist) hdata hotlist:gui_hotlist(*) buffer,count
    18:11:19                 | (31) hdata buffer:0x1594600/own_lines/last_line(-200)/data
                             | date,displayed,prefix,message,highlight,notify,tags_array
    18:11:19                 | (nicklist) nicklist 0x1594600
    18:11:19 <-- [1] weechat | obj: 144/236 bytes (39%, 0.14ms), id: last_read_lines
    18:11:19 <-- [1] weechat | obj: 114/175 bytes (35%, 0.12ms), id: hotlist
    18:11:19 <-- [1] weechat | obj: 682/3438 bytes (81%, 0.39ms), id: 31
    18:11:19 <-- [1] weechat | obj: 131/172 bytes (24%, 0.12ms), id: nicklist

    18:11:47 <-- [1] weechat | obj: 249/368 bytes (33%, 0.31ms), id: _buffer_localvar_changed

bob sends me a pm—works as expected

    18:12:12 <-- [1] weechat | obj: 251/350 bytes (29%, 0.18ms), id: _buffer_line_added

- WeeChat version: WeeChat 2.7-dev (git: v2.6-155-g8cde654c6)
- OS, distribution and version: Raspbian GNU/Linux 9 (stretch) Linux 4.19.42-v7+ armv7l GNU/Linux

P.S. before 8cde654c6f1376a1f9a3f5af5e75c2b36dc777e5, sending a message before buffer name change would yield 

    23:01:14 <-- [1] weechat | obj: 143/159 bytes (11%, 0.23ms), id: _buffer_title_changed
    23:01:14 <-- [1] weechat | obj: 247/341 bytes (28%, 0.29ms), id: _buffer_line_added

and after would yield

    23:01:28 <-- [1] weechat | obj: 143/159 bytes (11%, 0.23ms), id: _buffer_title_changed

**Comment by flashcode** [comment] 2019-11-18 19:04
This is not a bug, it works like that by design. If the buffer is renamed, the synced name does not match any more, and therefore nothing is sent to the relay client.
As you said, using the pointer solves the problem in this case (that's why both pointer and name are supported in sync command).
It would be complicated to track buffer name changes and auto sync them, that's maybe not what the client expect.
So I think we can leave things as-is and use the pointer for these cases.

**Comment by oakkitten** [comment] 2019-11-18 19:12
i'm not using full buffer names to sync though, i'm using pointers.

**Comment by flashcode** [comment] 2019-11-19 19:05
After digging the problem, in fact when you give a buffer pointer it's exactly like giving a name, because internally the relay plugin only uses names in the "sync" structure (so a pointer is converted to the buffer name, then added in this structure).
So after if the buffer is renamed, it does not match any more the old name.
This will require some changes in relay plugin in order to be fixed.
Waiting for a fix, the solution for now is to sync everything.

**Comment by flashcode** [comment] 2020-01-12 16:04
It should be fixed, please let me know if it's OK for you.

**Closed** 2020-01-12 16:03 UTC
Labels: bug, in progress
