### ISSUE TITLE
Weechat not installing via homebrew

### ISSUE THREAD

**Issue by zakiaziz** [weechat/weechat#957] opened 2017-04-21 15:03 UTC
I'm trying to install weechat on my mac via homebrew
```
$ brew install weechat --with-python --with-perl
```
which outputs this:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 6 taps (caskroom/cask, homebrew/core, homebrew/fuse, homebrew/php, homebrew/versions, josegonzalez/php).
==> New Formulae
afuse            bindfs           djmount          ext4fuse         gitfs            ifuse            ori              s3fs             sshconfigfs      xmount
archivemount     btfs             encfs            fuse-zip         goofys           mp3fs            rofs-filtered    securefs         tup
avfs             curlftpfs        ext2fuse         gcsfuse          historian        ntfs-3g          s3-backer        simple-mtpfs     wdfs
==> Updated Formulae
ansible                            curl ✔                             kobalt                             nagios-plugins                     schismtracker
artifactory                        dbt                                kubernetes-cli                     nativefier                         servus
aws-elasticbeanstalk               docker-machine-driver-xhyve        latex2rtf                          ncmpcpp                            sip
aws-sdk-cpp                        elasticsearch                      lcdf-typetools                     ocamlbuild                         source-highlight
awscli                             etcd                               ledger                             ocproxy                            stern
batik                              exiftool                           libcouchbase                       opencoarrays                       swiftformat
bear                               filebeat                           librdkafka                         osc                                tcpreplay
bind                               flashrom                           libsoup                            osquery                            terragrunt
bmake                              folly                              libtorrent-rasterbar               osrm-backend                       tesseract
boost                              freeling                           llnode                             packetbeat                         tippecanoe
boost-bcp                          gnupg-pkcs11-scd                   llvm@3.9                           paket                              tmux
boost-mpi                          grpc                               log4cpp                            par2                               todoman
boost-python                       guile                              logstash                           pdftoedn                           tomcat
byteman                            homebrew/php/php55-xdebug          lumo                               pick                               uhd
cake                               homebrew/php/php56-xdebug          macvim                             planck                             unicorn
capnp                              homebrew/php/php70-xdebug          menhir                             pmd                                unzip
catimg                             homebrew/php/php71-xdebug          mercurial                          poco                               vaulted
cfr-decompiler                     influxdb                           metaproxy                          purescript                         vim
collector-sidecar                  jmxtrans                           metricbeat                         pyexiv2                            watchexec
conan                              josegonzalez/php/php55-xdebug      mkvtoolnix                         pyinvoke                           wesnoth
consul                             josegonzalez/php/php56-xdebug      monit                              pyqt                               widelands
convox                             josegonzalez/php/php70-xdebug      mono                               q                                  wireguard-tools
crystal-lang                       josegonzalez/php/php71-xdebug      moreutils                          qemu                               zabbix
cucumber-cpp                       kibana                             mutt                               scala

==> Using the sandbox
==> Downloading https://weechat.org/files/src/weechat-1.7.tar.xz
Already downloaded: /Users/zakiaziz/Library/Caches/Homebrew/weechat-1.7.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/weechat/1.7 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_F
==> make install VERBOSE=1
Last 15 lines from /Users/zakiaziz/Library/Logs/Homebrew/weechat/02.make:
[ 51%] Building C object src/plugins/irc/CMakeFiles/irc.dir/irc-sasl.o
cd /tmp/weechat-20170421-35846-hl748b/weechat-1.7/build/src/plugins/irc && /usr/local/Homebrew/Library/Homebrew/shims/super/clang -DENABLE_NLS -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ICONV -DHAVE_ZLIB -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"1.7\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirc_EXPORTS -I/usr/local/include -I/tmp/weechat-20170421-35846-hl748b/weechat-1.7/build  -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -fPIC   -fPIC -fPIC -o CMakeFiles/irc.dir/irc-sasl.o   -c /tmp/weechat-20170421-35846-hl748b/weechat-1.7/src/plugins/irc/irc-sasl.c
[ 52%] Building C object src/plugins/irc/CMakeFiles/irc.dir/irc-server.o
cd /tmp/weechat-20170421-35846-hl748b/weechat-1.7/build/src/plugins/irc && /usr/local/Homebrew/Library/Homebrew/shims/super/clang -DENABLE_NLS -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ICONV -DHAVE_ZLIB -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"1.7\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirc_EXPORTS -I/usr/local/include -I/tmp/weechat-20170421-35846-hl748b/weechat-1.7/build  -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -fPIC   -fPIC -fPIC -o CMakeFiles/irc.dir/irc-server.o   -c /tmp/weechat-20170421-35846-hl748b/weechat-1.7/src/plugins/irc/irc-server.c
[ 52%] Building C object src/plugins/irc/CMakeFiles/irc.dir/irc-upgrade.o
cd /tmp/weechat-20170421-35846-hl748b/weechat-1.7/build/src/plugins/irc && /usr/local/Homebrew/Library/Homebrew/shims/super/clang -DENABLE_NLS -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ICONV -DHAVE_ZLIB -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"1.7\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirc_EXPORTS -I/usr/local/include -I/tmp/weechat-20170421-35846-hl748b/weechat-1.7/build  -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -fPIC   -fPIC -fPIC -o CMakeFiles/irc.dir/irc-upgrade.o   -c /tmp/weechat-20170421-35846-hl748b/weechat-1.7/src/plugins/irc/irc-upgrade.c
[ 53%] Linking C shared module irc.so
cd /tmp/weechat-20170421-35846-hl748b/weechat-1.7/build/src/plugins/irc && /usr/local/Cellar/cmake/3.8.0/bin/cmake -E cmake_link_script CMakeFiles/irc.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o irc.so CMakeFiles/irc.dir/irc.o CMakeFiles/irc.dir/irc-bar-item.o CMakeFiles/irc.dir/irc-buffer.o CMakeFiles/irc.dir/irc-channel.o CMakeFiles/irc.dir/irc-color.o CMakeFiles/irc.dir/irc-command.o CMakeFiles/irc.dir/irc-completion.o CMakeFiles/irc.dir/irc-config.o CMakeFiles/irc.dir/irc-ctcp.o CMakeFiles/irc.dir/irc-debug.o CMakeFiles/irc.dir/irc-ignore.o CMakeFiles/irc.dir/irc-info.o CMakeFiles/irc.dir/irc-input.o CMakeFiles/irc.dir/irc-message.o CMakeFiles/irc.dir/irc-mode.o CMakeFiles/irc.dir/irc-msgbuffer.o CMakeFiles/irc.dir/irc-nick.o CMakeFiles/irc.dir/irc-notify.o CMakeFiles/irc.dir/irc-protocol.o CMakeFiles/irc.dir/irc-raw.o CMakeFiles/irc.dir/irc-redirect.o CMakeFiles/irc.dir/irc-sasl.o CMakeFiles/irc.dir/irc-server.o CMakeFiles/irc.dir/irc-upgrade.o /usr/local/lib/libgnutls.dylib -L/usr/local/opt/libgcrypt/lib -lgcrypt -L/usr/local/opt/libgpg-error/lib -lgpg-error -lresolv
[ 53%] Built target irc
[ 53%] Linking C shared module perl.so
cd /tmp/weechat-20170421-35846-hl748b/weechat-1.7/build/src/plugins/perl && /usr/local/Cellar/cmake/3.8.0/bin/cmake -E cmake_link_script CMakeFiles/perl.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names      -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -o perl.so CMakeFiles/perl.dir/weechat-perl.o CMakeFiles/perl.dir/weechat-perl-api.o /System/Library/Perl/5.18/darwin-thread-multi-2level/CORE/libperl.dylib ../libweechat_plugins_scripts.a
[ 53%] Built target perl
make: *** [all] Error 2
```
I'm not familiar with what's going on in under the hood, but it seems like it's failing to compile.

Any idea what's going wrong?

**Comment by flashcode** [comment] 2017-04-21 16:30
Hi,
Is perl properly installed on your system? (in standard directories)
For Homebrew problems, I would recommend to report the problem to the Homebrew team.

**Comment by flashcode** [comment] 2017-04-29 08:09
Closing this issue, for me the problem is with Homebrew, not WeeChat.

**Closed by flashcode** 2017-04-29 08:09 UTC
Labels: bug, waiting info

**Comment by Cashlix** [comment] 2017-07-31 14:17
Can you elaborate on this? I'm running into the exact same error.
Brew doctor doesn't report any issues.

**Comment by Jarvvski** [comment] 2017-07-31 15:40
@Cashlix  try:

`brew install weechat --with-aspell --with-curl --with-python --with-perl --with-ruby --with-lua --with-guile`

**Comment by zakiaziz** [comment] 2017-08-01 01:15
@Jarvvski That fixed the issue for me!

**Comment by Jarvvski** [comment] 2017-08-02 11:22
No problem.
