### ISSUE TITLE
Relay plugin should gracefully handle IRCv3.2 CAP negotiation

### ISSUE THREAD

**Issue by echarlie** [weechat/weechat#1002] opened 2017-05-25 13:30 UTC
IRC relay does not handle arguments to ```CAP LS```, such as ```CAP LS 302``` specified in [IRCv3.2](http://ircv3.net/specs/core/capability-negotiation-3.2.html)

### To reproduce

Connect to Weechat's IRC relay using an IRCv3.2 compatible client (I'm currently using the [Mutter](https://www.mutterirc.com/) Beta). When the client attempts to negotiate CAP, Weechat doesn't respond with a list of capabilities.

It looks like this line in particular is the one causing issues: https://github.com/weechat/weechat/blob/master/src/plugins/relay/irc/relay-irc.c#L1233

### Current Version

WeeChat 1.8 [compiled on May 13 2017 20:11:19

### OS

Arch Linux

**Comment by flashcode** [comment] 2017-05-25 14:09
This is a duplicate of #995 and it's fixed in version 1.9-dev (will be in version 1.9).

**Closed** 2017-05-25 14:09 UTC
Labels: bug, duplicate

**Comment by echarlie** [comment] 2017-05-25 16:26
Missed that; sorry. Will build and test.
