### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Bysmyyr** [weechat/weechat#1093] opened 2017-10-30 05:53 UTC
I have got crashes about 3 times a week after 1.91 update(previous was something 1.6 or...) All these crashes are appeared after some irc command like /n

    WeeChat 1.9.1 
Debian GNU/Linux 8 \n \l
I have no scripts loaded

there is bt, maybe missing some info?

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./weechat'.
Program terminated with signal SIGBUS, Bus error.
#0  0x0000036ef1c7946f in irc_protocol_cb_part () from /home/users/bysmyyr/wee/lib/weechat/plugins/irc.so
(gdb) bt full
#0  0x0000036ef1c7946f in irc_protocol_cb_part () from /home/users/bysmyyr/wee/lib/weechat/plugins/irc.so
No symbol table info available.
#1  0x0000036ef1c8a69a in irc_protocol_recv_command () from /home/users/bysmyyr/wee/lib/weechat/plugins/irc.so
No symbol table info available.
#2  0x0000036ef1c96269 in irc_server_msgq_flush () from /home/users/bysmyyr/wee/lib/weechat/plugins/irc.so
No symbol table info available.
#3  0x0000036ef1c96836 in irc_server_recv_cb () from /home/users/bysmyyr/wee/lib/weechat/plugins/irc.so
No symbol table info available.
#4  0x000000000045209e in hook_fd_exec ()
No symbol table info available.
#5  0x00000000004af4e6 in gui_main_loop ()
No symbol table info available.
#6  0x0000000000422195 in main ()
No symbol table info available.

**Comment by Mikaela** [comment] 2017-10-31 19:09
There is strong suspicion that this is caused by [one of Kapsi's shell servers](https://www.kapsi.fi/english.html), it has affected previously stable WeeChats with no changes, ZNCs, TeamSpeak and Mumble.

The administration has been contacted, but I think they haven't been heard of yet.

**Comment by flashcode** [comment] 2017-11-04 09:40
Hi,
Please compile WeeChat with debug info and send the full backtrace again (with symbols).
On a SIGBUS error I'm not sure this is WeeChat fault, it may be a compilation issue (bad options in compiler for the target architecture maybe?)

**Comment by flashcode** [comment] 2019-02-25 23:05
Not enough info on the crash, closing the issue.

**Closed by flashcode** 2019-02-25 23:05 UTC
Labels: bug, waiting info
