### ISSUE TITLE
[IRCv3] Support echo-message

### ISSUE THREAD

**Issue by lord-re** [weechat/weechat#1424] opened 2019-11-15 17:39 UTC
## Feature description
Add support for [echo-message](https://ircv3.net/specs/extensions/echo-message-3.2) .

This is already supported by Charybdis, Inspircd, Oragono and Unrealircd.

**Comment by sim642** [comment] 2019-11-15 17:50
Duplicate of #139.

**Closed by sim642** 2019-11-15 17:50 UTC
Labels: enhancement
