### ISSUE TITLE
CMake error when compiling from source

### ISSUE THREAD

**Issue by nikoheikkila** [weechat/weechat#489] opened 2015-08-16 14:34 UTC
I cloned the latest version from GitHub and followed the instructions to compile. The `make` command, however, can't seem to find a correct script from build-scripts. The server is *Debian GNU/Linux 7.8 (wheezy)*.

I suspect this is related to commit fd1886e883968dbf372157644ce5664e75a6ff4b

Here's the complete output:

```
-- The C compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for include file langinfo.h
-- Looking for include file langinfo.h - found
-- Looking for include file sys/resource.h
-- Looking for include file sys/resource.h - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Looking for eat_newline_glitch
-- Looking for eat_newline_glitch - found
-- Looking for include file libintl.h
-- Looking for include file libintl.h - found
-- Looking for dgettext
-- Looking for dgettext - found
-- Found GCRYPT: -L/lib/x86_64-linux-gnu -lgcrypt
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.7")
-- Looking for iconv_open
-- Looking for iconv_open - found
-- Performing Test ICONV_2ARG_IS_CONST
-- Performing Test ICONV_2ARG_IS_CONST - Failed
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.26.0")
-- Looking for flock
-- Looking for flock - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for aspell_version_string
-- Looking for aspell_version_string - found
-- checking for one of the modules 'ruby-2.2;ruby-2.1;ruby-2.0;ruby-1.9;ruby-1.8'
-- checking for one of the modules 'lua5.3;lua-5.3;lua53;lua5.2;lua-5.2;lua52;lua5.1;lua-5.1;lua51;lua-5.0;lua5.0;lua50;lua'
--   found lua5.1, version 5.1.5
-- Found Tclsh: /usr/bin/tclsh (found version "8.5")
-- checking for one of the modules 'guile-2.0'
-- Found V8: /usr/lib/libv8.so
-- The CXX compiler identification is GNU 4.7.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file ncursesw/ncurses.h
-- Looking for include file ncursesw/ncurses.h - found
-- checking for one of the modules 'cpputest'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/users/elcynico/weechat/build
>> build master × make
Scanning dependencies of target version_git
make[2]: /home/users/elcynico/weechat/build-scripts/git-version.sh: Command not found
make[2]: *** [CMakeFiles/version_git] Error 127
make[1]: *** [CMakeFiles/version_git.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by flashcode** [comment] 2015-08-16 14:44
I tried to clone in a new directory, no such error.
Do you have a directory "build-scripts" in the cloned root directory?

**Comment by nikoheikkila** [comment] 2015-08-16 14:51
> I tried to clone in a new directory, no such error.

I removed the old directory as well and cloned into a new one. Didn't fix it. Strange.

> Do you have a directory "build-scripts" in the cloned root directory?

Yes. This is what the directory contains, permissions etc. should be right?

```
>> weechat master × ls build-scripts/
total 9.5K
drwxr-xr-x  2 elcynico users    4 Aug 16 17:24 .
drwxr-xr-x 11 elcynico users   31 Aug 16 17:25 ..
-rwxr-xr-x  1 elcynico users 2.3K Aug 16 17:24 build.sh
-rwxr-xr-x  1 elcynico users 2.6K Aug 16 17:24 git-version.sh
```

**Comment by flashcode** [comment] 2015-08-16 17:31
If you are building in a build directory (for cmake), try to either remove CMakeCache.txt or the build directory itself and try again.

**Comment by flashcode** [comment] 2015-08-16 17:36
And what commands are you using for the build?
I'll try exactly the same in a new cloned directory.

**Comment by nikoheikkila** [comment] 2015-08-16 18:16
Here are the commands in whole:

```bash
git clone https://github.com/weechat/weechat.git weechat-git
cd weechat-git
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.weechat -DCMAKE_BUILD_TYPE=Debug
make
```

No help checking out an earlier commit, either: `make[2]: /home/users/elcynico/weechat-git/scripts/git-version.sh: Command not found`

For your information, I tried compiling weechat on my MacBook Pro with same commands and there were no errors. So, there's something wrong with my server environment, I guess.

**Comment by nikoheikkila** [comment] 2015-08-16 21:29
@flashcode: I figured it out.

`cat -vt build-scripts/git-version.sh` showed that this script had ^M in the end of all its lines. So, I opened the file with vim and commanded `:set ff=unix` then saved and it compiled succesfully. Running 1.4-dev now.

What beats me is how those line-endings ended up inside the script in the first place…

**Comment by flashcode** [comment] 2015-08-17 05:11
Weird, I have no ^M at the end of lines in this script.
And since I develop only in Linux, I have no idea how I could even commit such ^M in repository.
Maybe related to git command on Mac ?
You could check other files as well.

So I'm closing the issue, it looks like the problem is not in WeeChat.

**Closed by flashcode** 2015-08-17 05:11 UTC
Labels: bug

**Comment by bendem** [comment] 2015-08-17 08:34
Yes, this is caused by a bad line ending configuration in git. You might want to check this out: https://help.github.com/articles/dealing-with-line-endings/
