### ISSUE TITLE
Filters which reference server names are not updated when a server is renamed

### ISSUE THREAD

**Issue by PaulW2U** [weechat/weechat#1870] opened 2023-01-10 12:39 UTC
## Bug summary
If I write a filter which applies to a specific server I find that it doesn't work if the server is subsequently renamed.

## Steps to reproduce

1. Create a filter that references a specific server
2. Test that it works
3. Rename the server

## Current behavior
Filter fails to work as it refers to the old server name

## Expected behavior
Filter works as the server name has been updated

## Suggested solutions
Update server names in filters when a server is renamed

## Additional information
Currently all filters which are specific to a renamed server have to be manually updated

---

- WeeChat version: 3.8
- OS, distribution and version: Ubuntu 22.04
- Terminal: Terminator
- Terminal multiplexer (screen/tmux/…/none): None

**Comment by weechatter** [comment] 2023-01-11 07:10
for me not a bug

**Comment by flashcode** [comment] 2023-01-11 07:16
Hi,

When you say a filter uses a server name, you mean something like this, where "libera" is the server name:

    /filter add test irc.libera.#weechat * some_regex

If yes, that's normal, when you rename a server, you must manually rename specific config where you are using them outside the irc plugin, for example filters, triggers, etc.

Not a bug for me, so I close this issue.

**Closed by flashcode** 2023-01-11 07:16 UTC
Labels: bug
