### ISSUE TITLE
/OPER (uppercase) is no longer a valid command (and probably other uppercase commands too)

### ISSUE THREAD

**Issue by Perdu** [weechat/weechat#2015] opened 2023-09-13 11:24 UTC
## Bug summary

/OPER leads to the follow error:
```
Command "OPER" unknown
```

## Discussion

From what I understand, due to the work on #1872 , uppercase commands are being removed from weechat for auto-completion reasons. I don't fully understand the rationale behind this, but it leads to confusing situations for users. For instance, bitlbee suggests users to run `/OPER` (upercase) to log in, which leads to an error in weechat (see https://github.com/bitlbee/bitlbee/pull/191).

[RFC](https://www.rfc-editor.org/rfc/rfc1459.html#section-4.1.5) mentions uppercase commands. Why remove them?

## Weechat version
Tested on 4.0.4

**Comment by flashcode** [comment] 2023-09-13 11:45
Hi,

This is not a bug, but a behavior which has changed in v4.0.0.

Now `/oper` and `/OPER` could be different commands, like on UN*X system commands.
Therefore the completion is made only with the exact case as well.

The RFC you mention is the command sent to the IRC server, even if it's often similar to the WeeChat command, this is not always the case, and the WeeChat command is not an IRC protocol command as described in the RFC (for example `/msg` sends `PRIVMSG` to the server, so it doesn't make sense to type `/MSG` anyway).

Most clients allow upper case commands, but there's no obligation to do so, as you don't have to know which IRC command is sent under the hood.

**Comment by weechatter** [comment] 2023-09-13 11:45
https://specs.weechat.org/specs/2023-001-case-sensitive-identifiers.html

**Comment by flashcode** [comment] 2023-09-14 15:25
Yes this is a deliberate choice, WeeChat doesn't aim to copy or be compatible with any other client, but it's still fully RFC compliant. Internal commands may have different name and/or case than the ones used in the protocol itself, not an issue for me.

Bitlbee or other software could change their docs to use lower case (which also works in irssi), or put a notice somewhere saying that some clients allow only lower or upper case commands, and that commands may differ from one client to another.

Otherwise, I think we can just close both issues as "won't fix".

**Closed** 2023-09-14 15:31 UTC
Labels: bug
