### ISSUE TITLE
/me actions shown as " ACTION stuffhere"

### ISSUE THREAD

**Issue by randomdude999** [weechat/weechat#614] opened 2015-12-01 13:41 UTC
The title kind of says it. When examining the raw server log, to is revealed that the action is surrounded by \x01s, which makes it quite easy to make a regular expression to match for it.

**Comment by flashcode** [comment] 2015-12-01 13:52
Purpose of raw server log is to show what is sent/received as raw data from/to IRC server.
And the IRC protocol uses `\x01ACTION xxx\x01` as format for `/me` actions.
Do you have a display with actions outside the raw server log in WeeChat?

**Comment by randomdude999** [comment] 2015-12-01 15:25
If someone uses /me in a chat room, the display shows " ACTION does that and that", not for example "someone does that and that"

**Comment by flashcode** [comment] 2015-12-01 16:19
For me the display of actions are OK in channels.
Could you please tell me how to reproduce the problem?
If possible, please tell me (see also Contributing.asciidoc for info to include in bug reports):
* your WeeChat version
* your operating system (with the version)
* the steps with a default config that leads to the problem.

Thanks.

**Comment by randomdude999** [comment] 2015-12-01 17:39
WeeChat 1.3
Linux (Ubuntu 15.10)
I have no idea what leads to this, however all /me messages display as mentioned above

**Comment by flashcode** [comment] 2015-12-01 20:55
Then without extra info I close the issue, I'm not able to reproduce the problem.

**Closed by flashcode** 2015-12-01 20:55 UTC
Labels: bug, waiting info
