### ISSUE TITLE
Nicklist forgets voiced status

### ISSUE THREAD

**Issue by kerozene** [weechat/weechat#368] opened 2015-03-22 08:51 UTC
After doing the following mode changes, the nicklist showed &lt;tmro&gt; as being unvoiced:
(On doing /names, the voice reappeared in the nicklist)
```
12:59:16                -- > Mode ##foochannel [+o tmro] by ChanServ
12:59:27                -- > Mode ##foochannel [-vvvv AAAA BBBB CCCC DDDD] by tmro
12:59:37                -- > Mode ##foochannel [-vvvv EEEE FFFF GGGG HHHH] by tmro
12:59:45                -- > Mode ##foochannel [-vvvv IIII JJJJ KKKK LLLL] by tmro
12:59:54                -- > Mode ##foochannel [-vvvv MMMM NNNN OOOO tmro] by tmro
13:00:02                -- > Mode ##foochannel [-vvvv PPPP QQQQ RRRR SSSS] by tmro
13:00:51                -- > Mode ##foochannel [+vvvv EEEE FFFF LLLL PPPP] by tmro
13:01:02                -- > Mode ##foochannel [+vv SSSS tmro] by tmro
13:01:09                -- > Nicks ##foochannel: [@ChanServ @tmro +EEEE +FFFF +LLLL +PPPP +SSSS      
                           > AAAA BBBB CCCC TTTT DDDD UUUU GGGG VVVV HHHH IIII JJJJ KKKK MMMM NNNN
                           > OOOO QQQQ RRRR]
13:01:09                -- > Channel ##foochannel: 24 nicks (2 ops, 5 voices, 17 normals)
13:06:20                -- > Mode ##foochannel [+v RRRR] by ChanServ
13:06:40                -- > Mode ##foochannel [-o tmro] by tmro
```
I tried to reproduce this effect with a smaller set of changes in a test channel but it didn't happen.

WeeChat 1.2-dev [compiled on Mar 17 2015 17:33:35]

**Comment by Mikaela** [comment] 2015-03-22 09:06
Which capabilities do you have enabled? I think this is duplicate of https://github.com/weechat/weechat/issues/320 and your issue is not having `multi-prefix` enabled.

To try it, add `multi-prefix` to `irc.server_default.capabilities` and either reconnect/restart or `/quote cap req multi-prefix` (and check the server buffer to see if it succeeded).

**Comment by Mikaela** [comment] 2015-03-22 09:09
You might also want to surround your paste with three backticks (```) to make it easier to read codeblock.

* https://guides.github.com/features/mastering-markdown/#examples (examples, codeblocks)

**Comment by Mikaela** [comment] 2015-03-22 09:23
\#ircv3 confirmed that this is caused by missing multi-prefix, so fixing #320 would fix this. Ping @flashcode .

```
2015-03-22 11:08:06+0200 < Mikaela> also could someone check that I am correct with https://github.com/weechat/weechat/issues/368 being caused by lack of multi-prefix?
2015-03-22 11:14:45+0200 < mt> I can't reproduce that, the infolist script also tells me that weechat stores and uses multi-prefix information
2015-03-22 11:16:02+0200 < Mikaela> multi-prefix is not enabled by default in WeeChat, neither is any other capability
2015-03-22 11:16:20+0200 < mt> well then that is the problem
2015-03-22 11:16:49+0200 < Mikaela> :)
2015-03-22 11:17:15+0200 < Aaron> one must set irc.server_default.capabilities or irc.server.foobar.capabilities
2015-03-22 11:17:32+0200 < Aaron> I have irc.server_default.capabilities = "multi-prefix,server-time,userhost-in-names"  (default: "")
2015-03-22 11:19:08+0200 < Mikaela> I have account-notify,away-notify,extended-join,multi-prefix,server-time,userhost-in-names,znc.in/server-time-iso
2015-03-22 11:19:14+0200 < mt> my default is multi-prefix only, but I should probably change that to account-notify,away-notify,extended-join,multi-prefix as that is what I use on most networks
```

**Comment by flashcode** [comment] 2015-03-22 09:35
The multi-prefix capability should not help for this problem, it should work fine without (both server and WeeChat remembers multiple prefix, even if only the higher one is displayed in WeeChat).

@kerozene: on which IRC server do you have the problem?

**Comment by kerozene** [comment] 2015-03-22 09:37
chat.freenode.net, I don't know which one I was connected to at the time or if that matters

**Comment by flashcode** [comment] 2015-03-22 09:57
Ah I see where is the problem, it's because of the `/names` which is updating all nick prefixes with the ones received in answer. And since multi-prefix is not enabled, the server sends `@` and WeeChat will overwrite current prefixes (`@` and `+`) with only `@`.
So if you have exactly same sequence without the command `/names` done, the nick `tmro` should be voiced at the end.

So the problem should be fixed by enabling multi-prefix, and in future WeeChat could ask that automatically (see #320).
Therefore, I'm closing this issue.

**Closed by flashcode** 2015-03-22 09:57 UTC
