### ISSUE TITLE
queue commands

### ISSUE THREAD

**Issue by L3RN3W** [weechat/weechat#1959] opened 2023-06-15 19:16 UTC
## Feature description
Can you add a queue for xfer similar to LFTP feature at https://lftp.yar.ru/lftp-man.html 

```
queue [-n num ] cmd

       Add  the  given  command to queue for sequential execution. Each site has its own queue. `-n'
       adds the command before the given item in the queue. Don't try to queue `cd'  or  `lcd'  comвЂђ
       mands,  it may confuse lftp. Instead do the cd/lcd before `queue' command, and it will rememвЂђ
       ber the place in which the command is to be done. It is possible to queue up an already  runвЂђ
       ning  job  by `queue wait <jobno>', but the job will continue execution even if it is not the
       first in queue.

       `queue stop' will stop the queue, it will not execute any new commands, but  already  running
       jobs  will continue to run. You can use `queue stop' to create an empty stopped queue. `queue
       start' will resume queue execution.  When you exit lftp, it will  start  all  stopped  queues
       automatically.

       `queue' with no arguments will either create a stopped queue or print queue status.

queue --delete|-d [index or wildcard expression]

       Delete one or more items from the queue. If no argument is given, the last entry in the queue
       is deleted.

       queue --move|-m <index or wildcard expression> [index]

       Move the given items before the given queue index, or to the end if no destination is given.

              -q   Be quiet.
              -v   Be verbose.
              -Q   Output in a format that can be used to re-queue. Useful with --delete.

       Examples:
              > get file &
              [1] get file
              > queue wait 1
              > queue get another_file
              > cd a_directory
              > queue get yet_another_file

              queue -d 3             Delete the third item in the queue.
              queue -m 6 4           Move the sixth item in the queue before the fourth.
              queue -m "get*zip" 1   Move all commands matching "get*zip" to the  beginning  of  the
                                     queue.  (The order of the items is preserved.)
              queue -d "get*zip"     Delete all commands matching "get*zip".

       quote cmd

       For  FTP  -  send the command uninterpreted. Use with caution - it can lead to unknown remote
       state and thus will cause reconnect. You cannot be sure  that  any  change  of  remote  state
       because of quoted command is solid - it can be reset by reconnect at any time.

       For  HTTP  -  specific  to HTTP action. Syntax: ``quote <command> [<args>]''.  Command may be
       ``set-cookie'' or ``post''.
              open http://www.site.net
              quote set-cookie "variable=value; othervar=othervalue"
              set http:post-content-type application/x-www-form-urlencoded
              quote post /cgi-bin/script.cgi "var=value&othervar=othervalue" > local_file

       For FISH - send the command uninterpreted. This can be used to execute arbitrary commands  on
       server.  The  command must not take input or print ### at new line beginning. If it does, the
       protocol will become out of sync.
              open fish://server
              quote find -name \*.zip
```

**Comment by flashcode** [comment] 2023-06-15 19:23
Hi,
This is a duplicate of #1681, please complete this issue if needed.

**Closed by flashcode** 2023-06-15 19:23 UTC
Labels: feature

**Comment by L3RN3W** [comment] 2023-06-15 19:50
This is similar but this request is for all commands not just xfer ;-)

**Comment by flashcode** [comment] 2023-06-15 19:56
There's a script to do this: `/script install cmdqueue.py`.

I think this could stay as a script, no need to have this in WeeChat itself.

**Comment by L3RN3W** [comment] 2023-06-15 19:59
Oh nice, did not know this existed =) But is there a script to do similar for xfer? To limit downloading one file at at time for example? Thanks.

**Comment by flashcode** [comment] 2023-06-15 20:01
I don't think so, you can search scripts about xfer with: `/script search xfer`.

**Comment by L3RN3W** [comment] 2023-06-15 20:12
I see, is it very hard to impliment something like #1960? I see you already have speed limit option with `xfer.network.speed_limit_recv` which is very useful.
