### ISSUE TITLE
Adding mbedtls as alternative to libgcrypt/gnutls

### ISSUE THREAD

**Issue by evelikov** [weechat/weechat#2182] opened 2024-09-10 15:13 UTC
### Feature description

Greetings all o/

As part of my venture to install weechat on size-constrained OpenWrt devices, I'm wondering how the team feels about adding mbedtls support as alternative to libcrypt/gnutls.

The project has been around for a while, has stable API and various projects provide support for it as an alternative. It's also around 2-3 times smaller.

Glancing over - the (g)crypt side of things should be fairly straight-forward, so I can send out a PR. Haven't looked at the networking side of things, plus my TLS/SSL knowledge is lack-lustre.

**Comment by flashcode** [comment] 2024-09-10 17:03
Hi,

I'm closing this as duplicate off #863 (see my comment: https://github.com/weechat/weechat/issues/863#issuecomment-1382701802).

**Closed** 2024-09-10 17:03 UTC
Labels: feature
