### ISSUE TITLE
Mask password entry in NickServ query buffer in same way as /msg NickServ IDENTIFY

### ISSUE THREAD

**Issue by blackbit42** [weechat/weechat#1727] opened 2021-12-08 20:26 UTC
## Feature description
weechat masks the password with asterisk when you authenticate with `/msg NickServ IDENTIFY yadayada`, as you type / paste. That is a very useful feature.
Providing the IDENTIFY password is equally possible in a query buffer with NickServ. There, the password is not masked.
I propose to align the behavior of NickServ query buffers with `/msg NickServ`.

**Comment by weechatter** [comment] 2021-12-09 08:59
hmm. for me it will be masked in query buffer as well.

Maybe try: /trigger restore cmd_pass cmd_pass_register

and what is your weechat version?

**Comment by flashcode** [comment] 2021-12-09 09:06
I think the problem is when you don't use the `/msg` command (eg: `/msg nickserv identify xxx`) but directly the message because you're in the query buffer, eg: `identify xxx` (such input is not masked by any trigger).

**Comment by blackbit42** [comment] 2021-12-09 09:08
> Maybe try: /trigger restore cmd_pass cmd_pass_register

No change.

> and what is your weechat version?

`WeeChat 3.4-dev [compiled on Nov 12 2021 00:05:31]`

**Comment by weechatter** [comment] 2021-12-10 08:38
I tested with "/msg nickserv identify" in query buffer! I always run the complete command, I don't distinguish between channel and query buffer for those commands.

**Comment by flashcode** [comment] 2023-06-04 12:01
This has already been fixed in 4.0.0-dev, password in self messages sent (for example in private buffer) are now hidden, thanks to commit ea38779c851a31e07f9718c28982c89072709af6.

**Closed by flashcode** 2023-06-04 12:01 UTC
Labels: feature
