### ISSUE TITLE
Option to convert multiline pastes into a single line by replacing newlines with spaces

### ISSUE THREAD

**Issue by mgedmin** [weechat/weechat#1419] opened 2019-11-07 13:06 UTC
## Feature description

Sometimes I want to paste a sentence I copied from a different terminal, and that sentence has a newline in the middle (because the man page text was wrapped or something).  When I paste it into weechat with the middle click, multi-line paste detection kicks in and I'm given two choices: send the multiline message or cancel the paste.

I'd like there to be a third option: join the lines (by replacing newlines with spaces), so I can edit it before sending.

It's possible that this makes sense only when there aren't too many lines in the paste (like 2 or 3), to avoid problems due to IRC message length limits.

**Comment by sim642** [comment] 2019-11-07 16:50
Duplicate of #1329.

**Closed** 2019-11-07 16:51 UTC
Labels: duplicate, enhancement
