### ISSUE TITLE
WeeChat 2.4-dev (git: v2.3-105-gb38b2abe3) crashes while using it with relay ( Plain connection)

### ISSUE THREAD

**Issue by ersuniljoshi** [weechat/weechat#1298] opened 2019-01-31 17:58 UTC
## Bug summary
weechat crashes

## Current behavior

weechat crashes

## Steps to reproduce

using it with relay , plain connection with glowing bear

## Desired behavior

It should not crash

## Suggested solutions

I dont have

## Additional information

---

- WeeChat version: WeeChat 2.4-dev (git: v2.3-105-gb38b2abe3)
- OS, distribution and version: Rasberry Pi 3 b+
→ uname -a
Linux sjrpi 4.14.90-v7+ #1183 SMP Fri Dec 21 14:03:50 GMT 2018 armv7l GNU/Linux

**Comment by ersuniljoshi** [comment] 2019-01-31 18:24
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {1024, 0, 1, 1991866260, 1990756016, 0, 0, 4294967295, 4, 0, 2123762552, 
            33963620, 33963624, 0, 2123762552, 1991754748, 2123762760, 33963620, 47377848, 
            1991864320, 41489800, 1990959904, 2123762600, 33838168, 33839191, 2123762600, 0, 1023, 
            33838168, 2123762768, 1, 922832}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x76a88824 in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {
              41489800, 1991864320, 1, 1996378112, 800868, 35665856, 35665856, 0, 35666264, 
              1991864320, 1995182460, 0, 1, 1991864320, 1, 1991864320, 1, 34078568, 1, 35696072, 
              41489800, 1993848820, 34001832, 0, 1, 33966648, 0, 934132, 1, 1, 1548950189, 0}}, 
          sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#2  0x0002eba4 in weechat_shutdown ()
No symbol table info available.
#3  <signal handler called>
No locals.
#4  strlen () at ../sysdeps/arm/armv6/strlen.S:26
No locals.
#5  0x76ad1928 in __GI___strdup (s=0x0) at strdup.c:41
        len = <optimized out>
        new = <optimized out>
#6  0x75b81600 in irc_modelist_item_new () from /usr/lib/arm-linux-gnueabihf/weechat/plugins/irc.so
No symbol table info available.
#7  0x75b80fd0 in irc_mode_channel_set () from /usr/lib/arm-linux-gnueabihf/weechat/plugins/irc.so
No symbol table info available.
#8  0x75b8a19c in irc_protocol_cb_mode () from /usr/lib/arm-linux-gnueabihf/weechat/plugins/irc.so
No symbol table info available.
#9  0x75b9b4b0 in irc_protocol_recv_command ()
   from /usr/lib/arm-linux-gnueabihf/weechat/plugins/irc.so
No symbol table info available.
#10 0x75ba4e18 in irc_server_msgq_flush () from /usr/lib/arm-linux-gnueabihf/weechat/plugins/irc.so
No symbol table info available.
#11 0x75ba985c in irc_server_recv_cb () from /usr/lib/arm-linux-gnueabihf/weechat/plugins/irc.so
No symbol table info available.
#12 0x00067c78 in hook_fd_exec ()
No symbol table info available.
#13 0x000a029c in gui_main_loop ()
No symbol table info available.
#14 0x0002e2dc in main ()
No symbol table info available.
Undefined command: "exit".  Try "help".
quit

**Comment by flashcode** [comment] 2019-01-31 20:11
Thanks for reporting, this is a duplicate of #1297 and will be fixed in a few minutes.

**Closed by flashcode** 2019-01-31 20:11 UTC
