### ISSUE TITLE
Callback to signal *,irc_in* does not receive IRCv3 tags

### ISSUE THREAD

**Issue by jazzpi** [weechat/weechat#787] opened 2016-08-26 22:15 UTC
Weechat version: WeeChat 1.5 [compiled on May 11 2016 07:10:34]
OS: Arch Linux

Load the following script:

``` python
import weechat

def test_ircin_cb(data, signal, signal_data):
    weechat.prnt("", repr(signal_data))
    return weechat.WEECHAT_RC_OK


weechat.register("test", "jazzpi", "0.1.0", "WTFPL", "test script", "", "")

weechat.hook_signal("*,irc_in_*", "test_ircin_cb", "")
```

Now compare this script's ouput (in main buffer) to the output in `/server raw` for messages containing IRCv3 tags - In `/server raw` they're included, in the script's output they are not.

**Comment by flashcode** [comment] 2016-08-27 07:43
I looked at code, and I confirm, only the message without tags is sent in `*,irc_in_*` signals.
This could be considered a bug or maybe as a limitation.
In my opinion, tags should be sent in these signals, but this can cause problems in many scripts that are not ready to receive tags in the message.

So I think we have 2 solutions (feel free to suggest more if needed):

1. send the tags in the signals, and then fix all scripts (I think lot of scripts are affected)
2. add another signal to send the tags, but this would be a hack and sending more signals is slower, so I'm not sure this is the best solution.

There is a `irc_message_parse` in API (see https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_info_get_hashtable) which is aware of tags, so scripts should use that (but many scripts are parsing the message themselves).

**Comment by jazzpi** [comment] 2016-08-27 09:06
FWIW the `irc_in_*` modifier does send tags, but using `*` as message selector doesn't actually work (which is another issue I guess?) and I guess you could always use a modifier instead of a signal. I don't know how they compare performance-wise, though.

**Comment by flashcode** [comment] 2016-08-27 12:09
Yes, stars are not supported in modifier, not a bug, but a limitation (bugs are missing features, no? :-D).
It can be added easily (please open another issue if needed).

**Comment by flashcode** [comment] 2016-08-27 12:10
For the signals and IRC tags, I think I'll add that in early devel of future 1.7 (immediately after release of 1.6), so this will let some time to script authors to update their scripts if needed.

**Comment by flashcode** [comment] 2017-01-15 07:13
I forgot to implement that, so I change the target version to 1.8.

**Comment by flashcode** [comment] 2017-05-06 13:59
Not enough time for the version 1.8, I changed the target version to 1.9 (this time I'll try to not forget to do that immediately after the release of 1.8!).

**Comment by flashcode** [comment] 2017-06-10 19:03
1.9 is mostly a bugfix release, moving this issue to 2.0.

**Comment by flashcode** [comment] 2017-11-29 08:34
Not enough time to implement this and check all scripts, moving this issue to 2.1.

**Comment by flashcode** [comment] 2018-03-25 18:14
Done.

Now the broken scripts can be fixed :)

**Closed by flashcode** 2018-03-25 18:14 UTC
Labels: enhancement, in progress
