### ISSUE TITLE
Weechat cannot install scripts

### ISSUE THREAD

**Issue by Christian-Nerd** [weechat/weechat#1863] opened 2022-12-17 01:11 UTC
## Bug summary
When trying to install scripts script stops at https://i.imgur.com/Gr8597r.png 

## Steps to reproduce

1. Install weechat via homebrew on mac os(I use MacOs Monterey v12.6)
2. Use the latest version of python(I use python 3.10.8)
3.  Use /script update or /script list

## Current behavior

https://i.imgur.com/qYjIYez.png
When using script update, install <script>(I used autosort.py), or list it stops at the ```weechat     | script: downloading list of scripts...``` part

## Expected behavior
It should do as https://weechat.org/files/doc/stable/weechat_user.en.html#scripts says succesfully install, updating and listing scripts.

## Additional information

---

- WeeChat version: 3.7.1
- OS, distribution and version: macOs Monterey 12.6
- Terminal: iterm2
- Terminal multiplexer (screen/tmux/…/none): tmux according to https://iterm2.com/documentation-tmux-integration.html

**Comment by flashcode** [comment] 2022-12-17 08:10
Hi,
This is a duplicate of #1723, can you please try suggested solution here (last comment)?
Please comment in the other issue if needed, and I close this one as duplicate.

**Closed** 2022-12-17 08:10 UTC
Labels: bug

**Comment by flashcode** [comment] 2023-09-11 06:20
Hi,
I added a different way to download scripts using threads, this should fix the issue.
See my comment here: https://github.com/weechat/weechat/issues/1723#issuecomment-1711448127
Please try, your feedback is important.
If the problem is fixed, this is going to be merged.
Thanks!

**Comment by Christian-Nerd** [comment] 2023-10-09 18:47
It doesn’t work.

**Comment by flashcode** [comment] 2023-10-09 19:32
It was merged on the master branch, you tried to build it?
You can check that `/debug hooks` displays count for url (last line before the total), to be sure hooks url are used, something like this:

```
/debug hooks

hooks in memory:
          command:  261
      command_run:    5
            timer:    8
               fd:    5
          process:    0
          connect:    0
             line:    0
            print:    3
           signal:  119
          hsignal:   10
           config:    7
       completion:  105
         modifier:   24
             info:   83
   info_hashtable:    4
         infolist:   41
            hdata:   51
            focus:    9
              url:    0
        ---------------
            total:  735
```

When you say it doesn't work, is it the same result, or slightly different behavior?
