### ISSUE TITLE
Run Through DNS Listings

### ISSUE THREAD

**Issue by ibrokemypie** [weechat/weechat#904] opened 2017-02-06 07:27 UTC
On weechat I often have issues where chat.freenode.net gets me irc: address "chat.freenode.net" not found and irc: error: nodename nor servname provided, or not known
I know it is neither a connection error nor a dns error as nslookup shows a massive list of ip's, and pinging etc works fine, but for some reason even after restarting it, Weechat does not connect unless I restart the computer. Weechat obviously does not try any of the other ip addresses, and if that is not possible, perhaps at least an option to clear weechat's dns cache would do.

**Comment by flashcode** [comment] 2017-02-06 09:45
Hi,
Which version of WeeChat are you using?
This problem is supposed to be fixed in version 1.6, see this PR: #771
I would recommend to upgrade to latest stable (1.7), and check if it's OK.

**Comment by ibrokemypie** [comment] 2017-02-06 10:07
Hey, currently on stable 1.7, macoss sierra

**Comment by flashcode** [comment] 2017-02-06 10:38
OK, so when does the problem happen?
After suspend mode, after some other event, ...?
Are you able to reproduce? (unfortunately I can not make any test on Mac OS X)

**Comment by ibrokemypie** [comment] 2017-02-06 10:55
Not entirely sure, doesnt seem to happen often, generally survives suspends, sleeps etc, but I guess it may be during sleep sometimes it happens, sleep being when left innactive while on power, opposed to closing lid etc. It isn't too common, the only problem really is that the only remedy it seems is to restart the mac

**Comment by flashcode** [comment] 2017-02-06 10:59
If restarting WeeChat (or doing `/upgrade`) does not help, I'm not sure if this is a WeeChat bug.

**Comment by ibrokemypie** [comment] 2017-02-06 11:09
Neither of those do work. Only weechat is affected though, everything else works fine

**Comment by flashcode** [comment] 2017-02-16 06:27
OK, then I mark this bug as "help wanted", since I have no way to test or reproduce that.

**Comment by Diftraku** [comment] 2017-11-12 11:25
I had a similar issue with one network where the name resolution failed temporarily during a reconnect (either NXDOMAIN from the DNS or complete network failure, unsure which one) and the server address refused to connect again with the same error of `irc: error: Name or service not known` even though the name resolves fine on the same server.

This apparently similar how Irssi does it and only resolves the server addresses on startup or when first connecting during the session.

I had to resort to `/upgrade` after I had another connection blip (complete loss of connection for long enough to disconnect) and multiple networks failed to reconnect with the same error. After the "upgrade", everything was back to normal and all networks connected normally.

Running Weechat 1.9 on Fedora Server 26

**Comment by nanonyme** [comment] 2018-06-26 20:19
@Diftraku  that sounds like a pretty wrong way to handle things since the hostname might well be a round-robin hostname and preresolving means you're effectively pinning yourself to same IP. Also it's entirely allowed (again, round-robin) for an individual IP address to stop operating completely at any point

**Comment by flashcode** [comment] 2019-08-10 07:33
I was not able to reproduce, if you have more information about the problem please let me know.
For now I close this issue.

**Closed by flashcode** 2019-08-10 07:33 UTC
Labels: bug, help wanted, waiting info
