### ISSUE TITLE
Semicolon in buffer name prevents modifier hook "weechat_print" from functioning as intended

### ISSUE THREAD

**Issue by flowbish** [weechat/weechat#651] opened 2016-01-09 12:49 UTC
Currently the modifier hook `weechat_print` send its modifier data as the string `"$plugin;$buffer;$tags"`, which can cause parsing issues if the buffer name contains a semicolon.

This issue arose using the script colorize_nicks.py in a buffer with a semicolon in the name e.g. "ponychat.#asdfjkl;". Since the current buffer's name was incorrectly parsed, no nicks on the buffer were colorized.

Spaces or newlines could be an alternative, though this would require all plugins using `weechat_print` to require changes (and afaik nothing actually stops a plugin from naming a buffer with a space or newline).

**Comment by flashcode** [comment] 2016-01-09 13:00
Hi,
This is a duplicate of #42, closing this one (feel free to add info into issue #42 if needed).

**Closed by flashcode** 2016-01-09 13:00 UTC
