### ISSUE TITLE
Consider a .weechatrc file, or less defaults in weechat.conf

### ISSUE THREAD

**Issue by seagreen** [weechat/weechat#678] opened 2016-02-05 06:02 UTC
I'd like to be able to look at my weechat settings and see what's I've changed from the default, but since `weechat.conf` is 600 lines this isn't easy. This would be a big change, but have you considered giving default values to the settings in `weechat.conf` and having it start out empty, or perhaps only with a dozen or so entries that the user is most likely to change?

Thanks for the nice program. I moved from irssi to WeeChat, and while irssi wasn't bad it was definitely an improvement.

**Comment by flashcode** [comment] 2016-02-05 06:28
This is a duplicate of #19 (please update this issue if needed).

And by the way in WeeChat it is NOT recommended to edit the config files by hand, you have `/set` or `/iset` (with script iset.pl) in WeeChat: the values are checked, and the changes are applied immediately.
And you have interactive help on all options as well, with their default values.
Editing the file by hand is definitely harder than editing options in WeeChat (it's of course still possible if you know what you do!).

**Closed by flashcode** 2016-02-05 06:28 UTC

**Comment by OmeGak** [comment] 2016-02-11 14:14
It's true that `/set` is pretty nice, but I think a .weechatrc-like file, a single entry-point, would make a lot of sense for versioning WeeChat config. Is that really what #19 is proposing?

**Comment by flashcode** [comment] 2016-02-15 13:16
@OmeGak : what do you mean by a "weechatrc-like file"?
You can already use versioning tool on weechat config files (*.conf).

**Comment by OmeGak** [comment] 2016-02-15 14:32
The problem with versioning `*.conf` files is that both default values and user customized values live within the same place. This makes quite cumbersome tracking what is actually **my** configuration and the reason why people end up sharing theirs in `/set` style ([example](https://pascalpoitras.com/my-weechat-configuration/)).

I gather that @pascalpoitras is a quite knowledgeable WeeChat user and, according to one of the comments in that post, his silver bullet for loading **his** configuration is:

> No just open weechat and paste the lines!

Honestly, I find that not at option since it requires user interaction. In order to make it automatic one can go through the hassle of feeding the config into WeeChat's FIFO pipe, which is pretty ugly as well. [InWee](https://github.com/susam/inwee) tries to make this process a bit prettier.

The question is, why not having a single `.weechatrc` file with the same sintax as `*.conf` files that simply overrides default values with user-defined ones? It's a very common pattern for configuring programs and will be a much more maintainable way of backing up user config.

**Comment by flashcode** [comment] 2016-02-15 16:33
The issue #19 should be a solution for your problem: purpose is to write only the options you changed in *.conf files.
Having another file to override the conf files seems "bloated" to me, and does not make sense because the conf files already have the changed options, so it would duplicate changes.

**Comment by OmeGak** [comment] 2016-02-16 09:29
It makes sense indeed in order not to duplicate changes. I'll be then looking forward for #19. :smile:

**Comment by klloe** [comment] 2017-05-04 17:10
I solved this issue with [autoconf.py](https://github.com/klloe/weechat-autoconf) script.
