### ISSUE TITLE
Xfer Simultaneous Downloads Quota

### ISSUE THREAD

**Issue by n0w3b** [weechat/weechat#2175] opened 2024-08-17 13:33 UTC
### Feature description

Feature request for simultaneous xfer downloads limit if option like `xfer.limit` is set. If i for example was to set `xfer.limit = 1` it would download one file at a time. Once one file completes downloading it would start another in xfer quota. This is very useful for downloading multiple files one by one, without having to have them download all at once. Thank you.

**Comment by flashcode** [comment] 2024-08-17 13:53
Hi,
Thanks for your feature request, this is a duplicate of #1960, please comment this one if you need to add information.

**Closed by flashcode** 2024-08-17 13:53 UTC
Labels: feature
