### ISSUE TITLE
Default underline key is wrong when old config in use (please fix config upgrades as concern keybinds)

### ISSUE THREAD

**Issue by ctrlcctrlv** [weechat/weechat#1924] opened 2023-05-07 20:19 UTC
## Bug summary

0x1F should be used for underline not 0x15.

## Steps to reproduce

1. c-Cu
2. Observe output of 0x15
3. Expect output of 0x1F ( https://modern.ircdocs.horse/formatting.html#underline )

## Current behavior

0x15

## Expected behavior

0x1F

## Suggested solutions

change to 0x1F

## Additional information

none

---

- WeeChat version: WeeChat 3.2 [compiled on Aug 15 2021 05:42:10]
- OS, distribution and version: Debian GNU/Linux 11 (bullseye)
- Terminal: kitty
- Terminal multiplexer (screen/tmux/…/none): tmux

**Comment by ctrlcctrlv** [comment] 2023-05-07 20:23
I've got more information.

I first configured WeeChat in…well, probably around 2011.

I just keep moving my config file.

d0832cd50e55c5307dac5cb933f024282a7ce5d0 fixed this issue and removed ^C-u for most users, adding ^C-_ (which I don't have).

Therefore, I am going to retitle this issue.

**Comment by flashcode** [comment] 2023-05-08 17:24
Hi,

The default key is OK since 0.4.3 (the commit you pointed).

The key bindings are not automatically upgraded because they can be customized by users.
Instead a note is put in release notes to do it manually, you can see it here: https://weechat.org/files/doc/weechat/ReleaseNotes-devel.html#v0.4.3_colors_messages

It is strongly recommended to read carefully release notes on each WeeChat upgrade, because sometimes manual actions are required.

So I close this issue as key bindings are not automatically fixed by design.

Note: in WeeChat 4.0.0-dev, you can now see easily key bindings changed with this command: `/fset d:weechat.key` (keys are now options).

**Closed by flashcode** 2023-05-08 17:24 UTC
Labels: bug

**Comment by ctrlcctrlv** [comment] 2023-05-08 18:15
Thanks @flashcode o/
