### ISSUE TITLE
Do not filter mode changes with smart_filter, when the changes affect your own user

### ISSUE THREAD

**Issue by m-wynn** [weechat/weechat#435] opened 2015-06-06 05:43 UTC
Currently, smart_filter filters out mode changes to your own user.  Messages like:
`-- | Mode #my_channel [+o me] by user_a`

If smart_filter would not filter these messages, people would be able to immediately see if a mode change has affected them.

**Comment by flashcode** [comment] 2015-06-06 08:11
This is a duplicate of #113, so I'm closing this issue.
If you have something to add, please comment on the issue #113.

**Closed by flashcode** 2015-06-06 08:11 UTC
