### ISSUE TITLE
irc plugin having a socket error and is unable to connect again after that

### ISSUE THREAD

**Issue by Porkepix** [weechat/weechat#952] opened 2017-04-13 11:47 UTC
Yesterday morning, my Weechat got disconnect from Freenode.

It issued the following error message on the disconnect `09:46 =!= irc: reading data on socket: error -54 Error in the pull function.`

Since this error happened, more than 24H hours ago, the connection on Freenode can't be established anymore and it's looping on this:

```
09:46 =!= irc: reading data on socket: error -54 Error in the pull function.
09:46 -- irc: disconnecting from server...
09:46 -- irc: disconnected from server
09:46 -- irc: reconnecting to server in 10 seconds
09:46 -- irc: reconnecting to server...
09:46 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:46 =!= irc: address "chat.freenode.net" not found
09:46 =!= irc: error: No address associated with hostname
09:46 -- irc: reconnecting to server in 20 seconds
09:46 -- irc: reconnecting to server...
09:46 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:46 =!= irc: address "chat.freenode.net" not found
09:46 =!= irc: error: No address associated with hostname
09:46 -- irc: reconnecting to server in 20 seconds
09:46 -- irc: reconnecting to server...
09:46 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:46 =!= irc: address "chat.freenode.net" not found
09:46 =!= irc: error: No address associated with hostname
09:46 -- irc: reconnecting to server in 40 seconds
09:47 -- irc: reconnecting to server...
09:47 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:47 =!= irc: address "chat.freenode.net" not found
09:47 =!= irc: error: No address associated with hostname
09:47 -- irc: reconnecting to server in 1 minute, 20 seconds
09:48 -- irc: reconnecting to server...
09:48 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:48 =!= irc: address "chat.freenode.net" not found
09:48 =!= irc: error: No address associated with hostname
09:48 -- irc: reconnecting to server in 2 minutes, 40 seconds
09:51 -- irc: reconnecting to server...
09:51 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:51 =!= irc: address "chat.freenode.net" not found
09:51 =!= irc: error: No address associated with hostname
09:51 -- irc: reconnecting to server in 5 minutes, 20 seconds
09:56 -- irc: reconnecting to server...
09:56 -- irc: connecting to server chat.freenode.net/6697 (SSL)...
09:56 =!= irc: address "chat.freenode.net" not found
09:56 =!= irc: error: No address associated with hostname
09:56 -- irc: reconnecting to server in 10 minutes

```

Other networks are fine and still working without any issue.

Looking after the error message in the code to try to have a clue, I crossed
https://github.com/weechat/weechat/blob/370fbeb5a39b0b168551c1dd6d23c02f60c32721/src/plugins/irc/irc-server.c#L2948 and https://github.com/weechat/weechat/blob/370fbeb5a39b0b168551c1dd6d23c02f60c32721/src/plugins/irc/irc-server.c#L2968 which made me wonder if an update on gnutls could be the culprit. I downgraded it without any change.

Appart from that, the domain name have no issues, I could nslookup it with success as well as contact it through telnet/openssl and so on.

This issue happened on the latest stable version of Weechat, on Archlinux.
As of now, I'm still having my Weechat stuck in this state, in case I could gather any useful information to help understand what the problem is.

**Comment by weechatter** [comment] 2017-04-13 15:07
As i already told you in #weechat. i can not reproduce it:

17:03 ℹ  irc: verbinde zum Server chat.freenode.net/6697 (SSL)...
17:03 ℹ  gnutls: Verbindung mittels geheimen 1024-Bit-Diffie-Hellman-Schlüssels hergestellt
17:03 ℹ  gnutls: empfange 2 Zertifikate
17:03 ℹ   - Zertifikat[1]-Information:
17:03 ℹ     - subject `CN=hobana.freenode.net', issuer `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', serial 0x032504e790e92a311fc356c71c6e1443be30, RSA key 4096 bits, signed using RSA-SHA256, activated `2017-03-20 05:13:00 UTC', expires `2017-06-18 05:13:00 UTC', SHA-1 fingerprint `de02b6246077a529b1ddb33a1253af09bc5f60d1'
17:03 ℹ   - Zertifikat[2]-Information:
17:03 ℹ     - subject `C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3', issuer `O=Digital Signature Trust Co.,CN=DST Root CA X3', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', SHA-1 fingerprint `e6a3b45b062d509b3382282d196efe97d5956ccb'
17:03 ⚠  gnutls: Peer-Zertifikat ist NICHT vertrauenswürdig
17:03 ⚠  gnutls: Der Aussteller für das Peer-Zertifikat ist unbekannt
17:03 ℹ  irc: Verbindung zu chat.freenode.net/6697 (81.18.73.123) hergestellt
17:03 ℹ  hobana.freenode.net: *** Looking up your hostname...
17:03 ℹ  hobana.freenode.net: *** Checking Ident
17:03 ℹ  hobana.freenode.net: *** No Ident response
17:03 ℹ  hobana.freenode.net: *** Found your hostname
17:03 ℹ  irc: Clientfähigkeit, Server unterstützt: account-notify extended-join identify-msg multi-prefix sasl
17:03 ℹ  irc: Clientfähigkeit, Anfrage: account-notify multi-prefix sasl
17:03 ℹ  irc: Clientfähigkeit, aktiviert: account-notify multi-prefix sasl
17:03 ℹ  You are now logged in as nils_2. (nils__2!nils_2@unaffiliated/nils-2/x-2480262)
17:03 ℹ  SASL authentication successful
17:03 ℹ  Welcome to the freenode Internet Relay Chat Network nils__2
17:03 ℹ  Your host is hobana.freenode.net[81.18.73.123/6697], running version ircd-seven-1.1.4
17:03 ℹ  This server was created Fri Jan 13 2017 at 00:03:11 UTC
17:03 ℹ  hobana.freenode.net ircd-seven-1.1.4 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
17:03 ℹ  CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
17:03 ℹ  CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 ETRACE WHOX SAFELIST :are supported by this server
17:03 ℹ  ELIST=CTU KNOCK CPRIVMSG CNOTICE :are supported by this server

**Comment by Porkepix** [comment] 2017-04-14 17:51
As discussed with @weechatter on IRC, adding freenode configuration to the issue.
I doubt anything in it can be the root cause of the problem though as it didn't changed for at least 18 months.

```
19:40 [server] (irc.conf) 19:40 irc.server.freenode.addresses = "chat.freenode.net/6697" (default if null: "") 19:40 irc.server.freenode.anti_flood_prio_high = null -> 2 19:40 irc.server.freenode.anti_flood_prio_low = null -> 2 19:40 irc.server.freenode.autoconnect = null -> off 19:40 irc.server.freenode.autojoin = null -> "" 19:40 irc.server.freenode.autoreconnect = null -> on 19:40 irc.server.freenode.autoreconnect_delay = null -> 10 19:40 irc.server.freenode.autorejoin = on (default if null: on) 19:40 irc.server.freenode.autorejoin_delay = null -> 30 19:40 irc.server.freenode.away_check = null -> 0 19:40 irc.server.freenode.away_check_max_nicks = null -> 25 19:40 irc.server.freenode.capabilities = null -> "" 19:40 irc.server.freenode.command = null -> "" 19:40 irc.server.freenode.command_delay = null -> 0 19:40 irc.server.freenode.connection_timeout = null -> 60 19:40 irc.server.freenode.ipv6 = null -> on 19:40 irc.server.freenode.local_hostname = null -> "" 19:40 irc.server.freenode.msg_kick = null -> "" 19:40 irc.server.freenode.msg_part = null -> "WeeChat ${info:version}" 19:40 irc.server.freenode.msg_quit = null -> "WeeChat ${info:version}" 19:40 irc.server.freenode.nicks = "Porkepix" 19:40 irc.server.freenode.nicks_alternate = null -> on 19:40 irc.server.freenode.notify = null -> "" 19:40 irc.server.freenode.password = null -> "" 19:40 irc.server.freenode.proxy = null -> "" 19:40 irc.server.freenode.realname = "Porkepix" (default if null: "") 19:40 irc.server.freenode.sasl_fail = null -> continue 19:40 irc.server.freenode.sasl_key = null -> "" 19:40 irc.server.freenode.sasl_mechanism = plain (default if null: plain) 19:40 irc.server.freenode.sasl_password = "${sec.data.freenode_password}" (default if null: "") 19:40 irc.server.freenode.sasl_timeout = null -> 15 19:40 irc.server.freenode.sasl_username = "Porkepix" (default if null: "") 19:40 irc.server.freenode.ssl = on (default if null: off) 19:40 irc.server.freenode.ssl_cert = null -> "" 19:40 irc.server.freenode.ssl_dhkey_size = null -> 2048 19:40 irc.server.freenode.ssl_fingerprint = null -> "" 19:40 irc.server.freenode.ssl_priorities = null -> "NORMAL:-VERS-SSL3.0" 19:40 irc.server.freenode.ssl_verify = null -> on 19:40 irc.server.freenode.usermode = null -> "" 19:40 irc.server.freenode.username = "Porkepix" 19:40 19:40 40 options (matching with "irc.server.freenode.*")
```

It was asked to join `/server raw` here too, but it's only going back to 1H earlier and contains nothing about freenode in it sadly, only things about other servers where there are no issues.

**Comment by FedericoCeratto** [comment] 2017-07-25 14:51
I'm having the same issue. The server is InspIRCd-2.0

**Comment by Porkepix** [comment] 2017-09-26 09:46
Just ran into this problem again, this time on Mozilla's IRC server and only this one. Restarting weechat did fixed the issue. I still can't understand what's causing that.
Any idea about what's possible to do to help track down the issue next time it happens?

**Comment by lhirlimann** [comment] 2017-09-26 12:44
Mozilla is also running InspIRcd

**Comment by flashcode** [comment] 2017-09-26 13:04
If a restart fixes the issue, maybe there's a bad cleaning of gnutls structures in weechat on disconnection.

**Comment by Porkepix** [comment] 2017-09-26 13:12
Is there anything I can do if the problem does reproduce one more time to be able to know if this is the source of the issue? Or do you already have an idea at something to check?

**Comment by flashcode** [comment] 2017-09-26 13:13
I have to check in source if there's something wrong or missing with gnutls on disconnection.

**Comment by flashcode** [comment] 2018-05-31 18:29
The PR #1196 might help with this issue? I'll try to merge that soon.

**Comment by roughnecks** [comment] 2018-08-24 12:16
Hello.

I'm getting the same error with weechat 2.2 on cygwin:
`freenode =!= | irc: reading data on socket: error -54 Error in the pull function.`

It happens at least one time per day; after that, weechat reconnects on its own and everything else looks  fine. If you need more info, just ask.

Thanks

**Comment by rostwald** [comment] 2018-08-29 16:01
Same Problem here - after running for 5 days weechat disconnected with ``irc: reading data on socket: error -54 Error in the pull function.``  and won't connect to any server since. In fact weechat doesn't even try to connect: a tcpdump doesn't show any outgoing connections on the given port(s).
Using any other IRC client works just fine.

**Comment by zacheryph** [comment] 2018-11-15 15:44
Weechat 2.2 on Alpine works fine. Updated docker image (alpine edge) with Weechat 2.3 and I now see this error too as soon as I start weechat.

**Comment by flashcode** [comment] 2018-11-15 15:59
@zacheryph: can you check if you're using the same GnuTLS version on both WeeChat version (with `/debug libs`)?

**Comment by zacheryph** [comment] 2018-11-15 16:11
I was able to resolve this. My image just takes edge and installs weechat (amongst other packages)
Digging into the image more and doing an update/upgrade, it purged libressl and weechat started working just fine.

Some clash between gnutls & libressl? :slightly_frowning_face:

**Comment by goofus** [comment] 2019-04-25 07:19
I just had this:
<pre>irc: reading data on socket: error -54 Error in the pull function.
irc: disconnecting from server...
irc: disconnected from server
irc: reconnecting to server in 10 seconds
irc: reconnecting to server...
irc: connecting to server ***.net/7000 (SSL)...
gnutls: connected using 2048-bit Diffie-Hellman shared secret exchange
gnutls: receiving 2 certificates
 - certificate[1] info:
 - certificate[2] info:
gnutls: peer's certificate is trusted
irc: connected to irc.***.net/7000 (***)
***.net: *** Looking up your hostname...
***.net: *** Found your hostname (***.net)
***.net: Welcome to ***             
Your host is ***.net, running version InspIRCd-2.0
***.net InspIRCd-2.0 BHILRSWcdgikorswx CDFIJLMNOPQRSTXYabcdefhijklmnopqrstuvwz FIJLXYabdefhjkloqvw
AWAYLEN=200 CALLERID=g CASEMAPPING=rfc1459 CHANMODES=IXbew,k,FJLdfjl,CDMNOPQRSTcimnprstuz CHANNELLEN=64 CHANTYPES=# CHARSET=ascii ELIST=MU ESILENCE EXCEPTS=e EXTBAN=,CNOQRSTUcjmprsz FNC INVEX=I :are supported by this server
KICKLEN=255 MAP MAXBANS=60 MAXCHANNELS=120 MAXPARA=32 MAXTARGETS=20 MODES=20 NAMESX NETWORK=Scratch-Network NICKLEN=31 OPERLOG PREFIX=(Yqaohv)!~&@%+ REMOVE :are supported by this server
SECURELIST SILENCE=32 SSL=***:6697 STATUSMSG=!~&@%+ TOPICLEN=307 UHNAMES USERIP VBANLIST WALLCHOPS WALLVOICES WATCH=32 :are supported by this server</pre>

Weechat 2.4 on rpi3

**Comment by flashcode** [comment] 2019-09-11 19:11
This could be caused by old libs used (like GnuTLS).
As I can not reproduce the issue and with no more activity, I close it.

**Closed by flashcode** 2019-09-11 19:11 UTC
Labels: bug, not reproduced
