### ISSUE TITLE
Buffer resetting at the end of search

### ISSUE THREAD

**Issue by nishansubedi** [weechat/weechat#338] opened 2015-02-20 22:25 UTC
when you search in a buffer using ctrl-r, is there a way to stay on that particular spot in the buffer when you exit? every time i exit out of search mode it resets the view position to where it was before search. it would be great to be able to stay in that particular position since this would make it possible to create a meta search feature.

**Comment by flashcode** [comment] 2015-02-21 06:52
Hi,
This is duplicate of #76, so I close this issue.

**Closed by flashcode** 2015-02-21 06:52 UTC
Labels: duplicate, enhancement
