### ISSUE TITLE
WeeChat doesn't handle Ace of Hearts/Ace of Spades in topic

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#379] opened 2015-03-29 17:32 UTC
_To be tested with other characters._

When you enter the bare display mode with those characters in topic, the one who set the topic appears on same line as the topic.

```
2015-03-29 20:24:21+0300 -- Topic for #weechat is "https://weechat.org/ | Latest stable version: 1.1.1 | English support channel, *ONLY* about WeeChat software | Please read docs before asking! | Bug reports are welcome ONLY for latest stable or devel | Off-topic chan: #weechat-offtopic | Fingerprint for gpg key used to sign packages: A9AB 5AB7 78FA 5C35 22FD 0378 F82F 4B16 DEC4 08F8"
```

vs

```
2015-03-29 20:25:21+0300 -- Topic for ##asexuality is "channel for aces  and people wondering their aceness | http://www.asexuality.org/wiki/index.php?title=asexuality | http://fyeahqueerplatoniczucchinis.tumblr.com/faq | http://swankivy.tumblr.com/asexualessays"-- Topic set by libbies (~libbies@unaffiliated/yeoz) on 2015-03-29 17:34:35+0300
```

![normal display](http://i.imgur.com/aWr09O9.png)

![bare display](http://i.imgur.com/BXGQbDc.png)

![bare display by nils_2](http://i.imgur.com/rPHSuRD.png)

**Comment by Mikaela** [comment] 2015-03-29 17:33
Oh and there is also https://github.com/weechat/weechat/issues/79 which causes my screenshots to not show the aces which are visible in nils's screenshot.

**Comment by flashcode** [comment] 2015-03-30 10:36
Can you please tell me the exact steps (commands, keys, ...) to reproduce the problem in a test channel?

**Comment by Mikaela** [comment] 2015-03-30 10:49
1. Join channel that has those in topic or add them to topic of some channel.
2. Press alt-l to enter bare display mode
3. You see that topic setter or someone who said something appears on same line as the /topic and this also happens if you attempt to copy-paste the topic.

**Comment by flashcode** [comment] 2015-03-30 11:06
I have to check, but if the problem is related to #79, this is going to be fixed in glibc (and then it's not a WeeChat bug).
In bare more, WeeChat doesn't use ncurses, but still uses wcswidth() to compute the number of lines needed to display a message.

But... I noticed some weird behavior in bare display, even without such chars, so I'll check too.

**Comment by Mikaela** [comment] 2015-03-30 11:11
I think nils_2 is using newer glibc or at least the characters are visible in their screenshot and the issue is visible also in it, so I don't think this is caused by the glibc.

Also if you happen to need the characters, they are `🂡` `🂱`.

If you are wondering why they were in the topic, both are asexual slang:

* Ace of Spades = aromantic asexual
* Ace of Hearts = romantic asexual
* ace = asexual

**Comment by flashcode** [comment] 2020-05-09 18:24
I can not reproduce the issue, these chars work fine for me in the topic.
So I close the issue.

**Closed by flashcode** 2020-05-09 18:24 UTC
Labels: bug
