### ISSUE TITLE
Certain characters show up in chat buffer, but not in nicklist.

### ISSUE THREAD

**Issue by megalithic** [weechat/weechat#348] opened 2015-03-06 19:08 UTC
the following set of characters show up in the chat buffer, but not in the nicklist:
`oןos`
instead, in the nicklist, we see:
`oos`

weechat 1.1.1 on OSX 10.10.2 in iTerm2 (Build 2.9.20150304-nightly) within tmux 1.9a

**Comment by megalithic** [comment] 2015-03-19 14:21
lol, i think i have a sickness.. i keep checking back to this single reported bug to check progress. i'm sure it's low priority, but man, this particular issue makes it really hard to highlight/auto-complete people :/

**Comment by flashcode** [comment] 2015-03-19 20:02
I just tried with such nick, this works fine for me: it displays fine in nicklist and in buffer.
Can you try another terminal, like urxvt or xterm?

And I can understand you want fast bug fixes, but I develop WeeChat and fix bugs on my spare time, this can take some weeks or even months for bugs with low priority (or not yet reproduced, like this one). Your help or patches are welcome to speed up things!

**Comment by megalithic** [comment] 2015-03-20 01:04
@flashcode oh I certainly understand this is not your job and I definitely didn't mean for my comment to come across like that. I appreciate you giving it a try. Unfortunately, being on a mac, I don't have ready access to urxvt or xterm.. running in osx.

you think bitlbee could cause this? i am using hipchat by way of bitlbee. i wonder, i'll try changing my nick to that or similar, but within an irc buffer.

thanks again @flashcode

**Comment by dequis** [comment] 2015-03-20 05:04
Just to confirm, that second character is [U+05DF: HEBREW LETTER FINAL NUN](http://www.fileformat.info/info/unicode/char/05df/index.htm) and the rest are ascii, right?

You aren't going to get that nick in normal irc networks, bitlbee probably lets you because you enabled `utf8_nicks`.

Also surely mac os should have more terminals than just iTerm2. Worst case you could get one of those homebrew/macports things and build an X11 based terminal from there. But this is likely to be a problem with your terminal, gotta discard that possibility first. 

Made this test case for you. Make netcat listen in localhost like this `nc -l localhost 6667`, make weechat connect to it, and when it's connected copy/paste the following block of text in the netcat input:

```
:localhost.localdomain 001 yournick :welcome
:localhost.localdomain 005 yournick PREFIX=(ohv)@%+ CHANTYPES=&# CHANMODES=,,,ntC NICKLEN=23 CHANNELLEN=23 NETWORK=BitlBee SAFELIST CASEMAPPING=rfc1459 MAXTARGETS=1 WATCH=128 FLOOD=0/9999 :are supported by this server
:yournick!yournick@localhost.localdomain JOIN :#channel
:localhost.localdomain 353 yournick = #channel :@yournick @root oןos
:localhost.localdomain 366 yournick #channel :End of /NAMES list
:root!root@localhost.localdomain PRIVMSG #channel :Welcome!
:oןos!someone@localhost.localdomain PRIVMSG #channel :Test!
```

I can't reproduce it either, so I don't really know if the test case is good enough:

![](http://dump.dequis.org/XgRoF.png)

Also how is this stopping you from tab completing people? I don't get it.

...oh god maybe it really is bitlbee's fault. Do you even have `utf8_nicks` enabled?

**Comment by flashcode** [comment] 2015-03-22 14:46
Some news about your problem?
If it's related to the terminal or to the bitlbee option, then I can just close this issue.

**Comment by megalithic** [comment] 2015-03-22 23:09
@dequis @flashcode that was it! i `set utf8_nicks true` in bitlbee and all is well. thanks a ton guys. this ticket can be closed!

**Closed** 2015-03-23 06:45 UTC
Labels: bug
