### ISSUE TITLE
Line tag `notify_highlight` is not present in IRC highlights

### ISSUE THREAD

**Issue by oakkitten** [weechat/weechat#1529] opened 2020-06-23 01:46 UTC
According to [the documentation](https://weechat.org/files/doc/stable/weechat_user.en.html#lines_tags),

> `notify_highlight` Buffer with line is added to hotlist with level "highlight".

It reads as though this tag should be present whenever the buffer is added to the hotlist with the level "highlight". Instead, `notify_message` tag is present.

In relay, we are using line highlight information for several purposes, among those are painting text with highlight color and notifying the user. We are usually getting highlight information from `highlight` field, but I suppose it's a bad thing to do and instead we should be getting it from `notify_highlight` tag. The former can be used for coloring text, and the latter for notifications. This way we can properly deal with highlights that come from backlog, such as those produced by wee-slack plugin.

If this is intended behavior, perhaps the documentation could be fixed. It's not clear what to with a line that has both `notify_message` tag and `highlight` field. Add is as a highlight? Add it as a message?

### Current behavior

In IRC highlights, `notify_message` tag is present instead of `notify_highlight`

### Expected behavior

In IRC highlights, `notify_highlight` tag should be present

### Suggested solutions

Make all highlights that make it to the hotlist have the tag `notify_highlight` or clarify the documentation

---

- WeeChat version: WeeChat 2.8-dev (git: v2.7-48-g95e34c71d)
- OS, distribution and version: Raspbian GNU/Linux 10 (buster)

**Comment by flashcode** [comment] 2020-06-23 06:31
Hi,

This is not a bug, the tag "notify_xxx" is the "initial" level for the line, not the final level WeeChat will use for the line. I'll clarify the doc to mention it's the initial notify level, and according to highlight settings in WeeChat, the final level can be different.

The real notify level for the line is stored in "notify_level" variable inside the line. But I just noticed this variable, which was added in version 2.3 for hook_line is currently not sent to the relay client: https://weechat.org/files/doc/devel/weechat_relay_protocol.en.html#message_buffer_line_added. I'll send it to the client as it's a relevant info.

**Comment by flashcode** [comment] 2020-06-23 06:41
Sorry after checking I was wrong, the "notify_level" in line is computed with the tag received, it's not the level used for hotlist (this one is computed on the fly and not stored in the line).

So you can use either the tag or this "notify_level" (that will be added soon), and the existing variable "highlight", to know if there's a highlight on the line.

**Comment by flashcode** [comment] 2020-06-23 06:55
By the way, it's better to use the "notify_level" variable, because its value is also affected by the max hotlist level you can set for some nicks (so not only tags in line): https://weechat.org/files/doc/devel/weechat_user.en.html#max_hotlist_level_nicks

**Comment by oakkitten** [comment] 2020-06-23 15:43
so what should i do if the line has the `highlight` field but doesn't have `notify_highlight` tag? should i notify the user or not?

**Comment by flashcode** [comment] 2020-06-23 17:41
@oakkitten: yes, the `highlight` field should be used. Messages from users have only tag `notify_message` and then if WeeChat detects a highlight in the line (ie your nick mentioned), the `highlight` field is set to 1.

You should not use `notify_xxx` tags at all for notifications, it's just used to know the type of message (join/quit, from user, private, etc.).

**Comment by oakkitten** [comment] 2020-06-23 18:24
if i don't use `notify_xxx` tags for notifications, how do i tell if i should notify user of a private message that doesn't happen in a private buffer, such as a notice?

and how can scripts such as wee-slack, or irc plugin, when it finally supports ircv3, display backlog messages with highlights but without notifying users?

**Comment by trygveaa** [comment] 2020-06-23 19:04
@flashcode: When `slack.py` loads it fetches earlier history for each channel and dm, so you can see previous messages in the channel. On each line it prints from the history, it sets `notify_none` and turns off `print_hooks_enabled` so the user is not notified for old messages. It also sets the buffer properties `unread` to `""` and `hotlist` to `-1` after the line has been printed.

This works fine for weechat itself, however it doesn't work for relay clients. As far as I understand, relays can only read the tags, and don't get messages when `print_hooks_enabled` are changed, or when `unread` or `hotlist` are set.

What should the relay client do in this case? I don't think it should notify for the messages, because you wouldn't get a notification when using weechat directly (and in the case for slack, we never want to notify for the history). But if it shouldn't notify for the message, how can it know that if not by reading the `notify_none` tag?

Is there a better way to print lines which shouldn't send notifications? Should `slack.py` do something different?

**Comment by flashcode** [comment] 2020-06-23 21:00
@trygveaa: yes the tag `notify_none` is designed to turn off notification for the line. But why do you need to play with `print_hooks_enabled`, in addition to this tag?
Anyway I'm not sure this issue is the best place to discuss that, this is a different problem/question.

**Comment by trygveaa** [comment] 2020-06-23 22:54
> yes the tag notify_none is designed to turn off notification for the line.

But in your previous comment, you said that `notify_xxx` tags shouldn't be used for notifications? And even when you set `notify_none`, the line will still be added to the hotlist if it's a highlight.

> But why do you need to play with print_hooks_enabled, in addition to this tag?

Because many notify scripts and the default beep trigger doesn't check notify tags. They just check if it's a highlight or a private message.

> Anyway I'm not sure this issue is the best place to discuss that, this is a different problem/question.

It's related. I spoke with @oakkitten on irc, and he asked me to comment here. What I described with what `slack.py` does is why he opened the issue in the first place as far as I've understood, because it's not working with relay clients.

**Comment by oakkitten** [comment] 2020-06-26 18:00
although not a perfect solution, wee-slack's problem could be somewhat mitigated by temporarily changing the notify level of the channel. this, however, will still be broken in relays because relays are not notified of notify levels changing: #593

**Comment by flashcode** [comment] 2020-07-20 19:55
So I just committed the following changes:

1. If a line has a tag `notify_none`:
    - the line is not added to hotlist, even if it has a highlight,
    - the trigger "beep" does nothing: the command is not executed any more.
2. I clarified the tags "notify_xxx" in chapter on lines tags in the user's guide: https://weechat.org/files/doc/devel/weechat_user.en.html#lines_tags

**Comment by trygveaa** [comment] 2020-07-20 22:56
Thanks!

**Comment by oakkitten** [comment] 2020-08-01 22:09
should `notify_level` value of -1 be treated similarly to `notify_none`? is it `if notify_none: do not notify` or `if notify_none or notify_level == -1: do not notify` or pehaps i should always expect `notify_level` to be -1 when there's `notify_none`?

**Comment by flashcode** [comment] 2020-08-02 07:58
@oakkitten: as you can see here: https://github.com/weechat/weechat/blob/master/src/gui/gui-line.c#L1248, if tag `notify_none`, the `notify_level` is set to `-1`. So you can expect -1 when notify_none is present.

For your example with both notify_none and notify_highlight, this is related to the line I mentioned above: if there are multiple tags with "notify_xxx", the last one wins. It could be considered as a bug or a feature but currently there's no priority on notify tags (a line should not be displayed with multiple notify_xxx tags, this doesn't make sense).

**Comment by trygveaa** [comment] 2020-08-02 10:08
@flashcode: I see that when a line gets a highlight, but doesn't have `notify_highlight` set, `notify_level` isn't set to 3. Would it make sense to set `notify_level` to 3 in this case, so you don't have to check both `notify_level` and `highlight`?

**Comment by flashcode** [comment] 2020-08-02 10:22
Yes it's because the `notify_level` is set with the `notify_xxx` tag, before we look if there's a highlight.
So maybe I could adjust it later if a highlight is detected, I'll check if it's easy to do and if there are no compatibility issues with that (I think to existing plugins/scripts).

**Closed** 2020-08-15 12:03 UTC
Labels: bug, in progress
