### ISSUE TITLE
CMake should not fail silently if Python is not found

### ISSUE THREAD

**Issue by ctrlcctrlv** [weechat/weechat#1397] opened 2019-08-31 06:35 UTC
I am trying to build the `master` branch on FreeBSD 12.0-RELEASE.

https://github.com/weechat/weechat/blob/63902ef52d471bee1d4946f98db6d8e93d105805/src/plugins/CMakeLists.txt#L99-L104

If the user demands Python via:

```
master# cmake . -DENABLE_PYTHON=ON -DENABLE_PYTHON2=ON -GNinja                                                                
-- checking for one of the modules 'guile-2.0'                                                                                
-- checking for one of the modules 'php7'                                                                                     
-- checking for one of the modules 'ncursesw'                                                                                 
-- checking for one of the modules 'cpputest'                                                                                 
-- Configuring done                                                                                                           
-- Generating done                                                                                                            
-- Build files have been written to: /root/weechat             
```                                                               

User is just ignored if Python cannot be found, and a deficient binary will be built. I believe this to be a bug. If user explicitly requests build with Python, CMake should not even try to build if it cannot find Python.

**Comment by flashcode** [comment] 2019-08-31 06:55
Hi,
Thanks for reporting this issue, this is planned to improve that in future.
This issue is a duplicate of #916, so I close this one in favor of the other (the problem happens with all libraries, not only Python).

**Closed by flashcode** 2019-08-31 06:55 UTC
Labels: enhancement

**Comment by flashcode** [comment] 2019-08-31 07:17
And there's also a pull request: #956.
