### ISSUE TITLE
Tests fail to build on Darwin

### ISSUE THREAD

**Issue by ncfavier** [weechat/weechat#1834] opened 2022-10-10 18:56 UTC
While trying to `ENABLE_TESTS` [in nixpkgs](https://github.com/NixOS/nixpkgs/pull/195239/files#diff-781f7463177fa6e77c3fa3ec16b88d2871c279589f33012047474d36263aa49dR54), I noticed that they fail to build on Darwin (i.e. with clang). [Full error log](https://gist.github.com/ncfavier/ca5ab64e667e5b2e72b11d59c24c88fa).

Looks like linker flags are being passed to the wrong program, or something?

I don't think this matters a lot so if you don't care feel free to close.

**Comment by flashcode** [comment] 2022-10-12 11:48
Hi,

With the output, this is not clear which symbol is missing.

Can you please try with older releases and check if it works?
If working fine, then you could find the guilty commit using `git bisect`.

Unfortunately, I have no access to Darwin and I'm not able to reproduce this issue on my side, even by using clang compiler.

**Comment by ncfavier** [comment] 2022-10-13 08:39
Me neither 😅 and I don't feel like abusing the nixpkgs CI to test this, so...

**Comment by flashcode** [comment] 2023-04-23 15:16
Not enough information, closing the issue.
Feel free to comment or open another issue if you have more information, thanks.

**Closed by flashcode** 2023-04-23 15:16 UTC
Labels: bug, waiting info
